NamseEnt/namseent

luda/editor/client/src/index.ts
luda/editor/client/src/render.ts
luda/editor/client/src/subtitleEditor/renderPreview.ts
luda/editor/client/src/subtitleEditor/renderPropertyEditor/renderCheckboxInput.ts
luda/editor/client/src/subtitleEditor/renderPropertyEditor/renderColorInput/renderAlphaSlider.ts
luda/editor/client/src/subtitleEditor/renderPropertyEditor/renderColorInput/renderColorInput.ts
luda/editor/client/src/subtitleEditor/renderPropertyEditor/renderColorInput/renderHueSlider.ts
luda/editor/client/src/subtitleEditor/renderPropertyEditor/renderColorInput/renderLightnessSlider.ts
luda/editor/client/src/subtitleEditor/renderPropertyEditor/renderColorInput/renderSaturationSlider.ts
luda/editor/client/src/subtitleEditor/renderPropertyEditor/renderColorInput/renderSlider.ts
luda/editor/client/src/subtitleEditor/renderPropertyEditor/renderNumberInput.ts
luda/editor/client/src/subtitleEditor/renderPropertyEditor/renderPropertyEditor.ts
luda/editor/client/src/subtitleEditor/renderPropertyEditor/renderRows.ts
luda/editor/client/src/subtitleEditor/renderPropertyEditor/renderTextInput.ts
luda/editor/client/src/subtitleEditor/renderSubtitleEditor.ts
luda/editor/client/src/subtitleEditor/type.ts
namui/src/ColorUtil.ts
namui/src/getGcCanvasKitPackage.ts

- Subtitle Preview
- Edit subtitle properties
- Font `text` `serif` `size` `color`
- Background `color`
- Border `color` `width`
- Drop shadow `color` `x` `y`

Add subtitle editor

---

luda/editor/client/src/timeline/renderSubtitleTrackBody.ts

If right button up on subtitle clip, It opens clip context menu, Not track context menu
closes #23

Remove subtitle clip from context menu

---

luda/editor/client/src/saver/saver.ts

~~I found an error, so I'll reverts it.~~
Fix saver to update lastValueString on save

Fix saver to update lastValueString on save

---

README.md

> English follows
굳이 만들고 싶진 않았는데, 언젠간 해야할 것 같아서 올립니다.
법적인 검토사항은 지금은 아직 고려하지 않으려고 합니다.
I didn't really want to make it, but I think I'll have to do it someday, so I'm posting it.
Legal considerations are not yet to be considered at this time.

Add license to main README.md

---

luda-editor/luda-editor-client/src/editor/clip_editor/camera_clip_editor/mod.rs
luda-editor/luda-editor-client/src/editor/clip_editor/camera_clip_editor/preview.rs
luda-editor/luda-editor-client/src/editor/clip_editor/camera_clip_editor/wysiwyg_editor/mod.rs
luda-editor/luda-editor-client/src/editor/types/camera_angle.rs
luda-editor/luda-editor-client/src/editor/types/mod.rs
namui/src/namui/render/types.rs

- Add preview in camera clip editor 6f31829d22005f97953c9227a71dd9c22ef9c7b6
- Get Xy or Wh from Xywh Rect 01fa38ea5e827699ca5f0b6913144311c1ed06ea
https://user-images.githubusercontent.com/3580430/147807319-c9809c3f-efc2-41f5-b1fa-e5cbe697943f.mp4

Add preview in camera clip editor

---

luda-editor/luda-editor-client/src/editor/clip_editor/mod.rs
luda-editor/luda-editor-client/src/editor/events.rs
luda-editor/luda-editor-client/src/editor/job/mod.rs
luda-editor/luda-editor-client/src/editor/job/move_subtitle_clip.rs
luda-editor/luda-editor-client/src/editor/job/wysiwyg_crop_image.rs
luda-editor/luda-editor-client/src/editor/job/wysiwyg_move_image.rs
luda-editor/luda-editor-client/src/editor/job/wysiwyg_resize_image.rs
luda-editor/luda-editor-client/src/editor/mod.rs
luda-editor/luda-editor-client/src/editor/timeline/mod.rs
luda-editor/luda-editor-client/src/editor/timeline/timeline_body/mod.rs
luda-editor/luda-editor-client/src/editor/timeline/timeline_body/track_body/camera_track_body/camera_clip_body.rs
luda-editor/luda-editor-client/src/editor/timeline/timeline_body/track_body/camera_track_body/mod.rs
luda-editor/luda-editor-client/src/editor/timeline/timeline_body/track_body/mod.rs
luda-editor/luda-editor-client/src/editor/timeline/timeline_body/track_body/subtitle_track_body/mod.rs
luda-editor/luda-editor-client/src/editor/timeline/timeline_body/track_body/subtitle_track_body/subtitle_clip_body.rs
luda-editor/luda-editor-client/src/editor/types/mod.rs
luda-editor/luda-editor-client/src/editor/types/pixel_size.rs
namseent.code-workspace
namui/Cargo.toml
namui/src/namui/mod.rs
namui/src/namui/skia/types.rs
namui/src/namui/skia/web/canvas_kit/paint.rs
namui/src/namui/skia/web/canvas_kit/path.rs
namui/src/namui/skia/web/paint.rs
namui/src/namui/skia/web/path.rs

- Set paint stroke cap - 9a6c4b2
- Close path - 2e7d300
- Brighten color with hsl - 4de3c4b
- Render subtitle track - 0dc693a
- Get mutable clip instead of update whole clip - c73e3dd
- Move subtitle clip by dragging head - 0d2e8d5
Please merge with **rebase**, not squash because I think when we put some of namui update, rebasing is better than squash. Squash shallow all of things in one commit message, so it should be used in individual changes.

Rendering and moving subtitle clips

---

luda-editor/luda-editor-client/src/editor/clip_editor/camera_clip_editor/image_browser/back_button.rs
luda-editor/luda-editor-client/src/editor/clip_editor/camera_clip_editor/image_browser/browser_item.rs
luda-editor/luda-editor-client/src/editor/clip_editor/camera_clip_editor/wysiwyg_editor/cropper.rs
luda-editor/luda-editor-client/src/editor/clip_editor/camera_clip_editor/wysiwyg_editor/mod.rs
luda-editor/luda-editor-client/src/editor/clip_editor/camera_clip_editor/wysiwyg_editor/resizer.rs
luda-editor/luda-editor-client/src/editor/timeline/timeline_body/track_body/subtitle_track_body/subtitle_clip_body.rs
luda-editor/luda-editor-client/src/editor/types/camera_angle.rs
namui/Cargo.toml
namui/src/namui/draw/image.rs
namui/src/namui/draw/mod.rs
namui/src/namui/draw/path.rs
namui/src/namui/draw/text.rs
namui/src/namui/mod.rs
namui/src/namui/render/image.rs
namui/src/namui/render/path.rs
namui/src/namui/render/rect.rs
namui/src/namui/render/text.rs
namui/src/namui/skia/base/mod.rs
namui/src/namui/skia/base/paint_builder.rs
namui/src/namui/skia/types.rs
namui/src/namui/skia/web/color_filter.rs
namui/src/namui/skia/web/font.rs
namui/src/namui/skia/web/paint.rs

Like previous pull request (Optimize path by PathBuilder #56), this pull reuqest optimize paint with PaintBuilder in same way.
Only one thing different is Paint doesn't need to save commands unlike Path. So it's much simpler than Path.

Optimize paint with PaintBuilder

---

luda-editor/luda-editor-client/src/app/app.rs

I think todo means what we will to do someday. I used todo! macro as unreachable but I think it is very different. So I replace some todo macros with unreachable.

Change unreachable from todo

---

luda-editor/luda-editor-client/Cargo.toml
luda-editor/luda-editor-client/src/lib.rs
namui/src/namui/namui_web/mod.rs

I found that I didn't turn on panic console log. I REALLY DIDN'T KNOW THAT SO I THOUGHT WASM IS SUCKS... HAHAHAHAHAHAHAHAHAHAHAHAHAHA

Set panic console log

---

luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/back_button.rs
luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/browser_item.rs
luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/mod.rs
luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/types.rs
luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/mod.rs
luda-editor/luda-editor-client/src/app/editor/clip_editor/mod.rs
luda-editor/luda-editor-client/src/app/editor/events.rs
luda-editor/luda-editor-client/src/app/editor/job/move_camera_clip.rs
luda-editor/luda-editor-client/src/app/editor/job/move_subtitle_clip.rs
luda-editor/luda-editor-client/src/app/editor/job/wysiwyg_crop_image.rs
luda-editor/luda-editor-client/src/app/editor/job/wysiwyg_move_image.rs
luda-editor/luda-editor-client/src/app/editor/job/wysiwyg_resize_image.rs
luda-editor/luda-editor-client/src/app/editor/mod.rs
luda-editor/luda-editor-client/src/app/editor/timeline/mod.rs
luda-editor/luda-editor-client/src/app/types/mod.rs

- 38e66fb7fff4e34f44811eb3e03c74674aa479b0
- Replace string key with enum key for image browser to make it better code quality
- Open camera clip's image directory when open image browser
- Update camera angle image : 21fdb81bb9dbf73cf511e80be692d570e8efced2
Merge must be in **squash**

Update camera angle image using image browser

---

luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/scroll.rs
luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/wysiwyg_editor/cropper.rs
luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/wysiwyg_editor/mod.rs
luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/wysiwyg_editor/resizer.rs
namui/src/namui/skia/types.rs

I renamed gray_scale with to grayscale. It's kind of `filename vs file name` problem i think. I HATE ENGLISHHHHHH

Rename gary_scale to grayscale

---

luda-editor/luda-editor-client/src/app/editor/timeline/time_ruler/gradations.rs
luda-editor/luda-editor-client/src/app/editor/timeline/time_ruler/mod.rs
luda-editor/luda-editor-client/src/app/editor/timeline/time_ruler/time_text.rs
luda-editor/luda-editor-client/src/app/types/time.rs

Port time ruler's gradation and texts from typescript to rust.

Render time ruler gradations and texts

---

luda-editor/luda-editor-client/src/app/sequence_list/load_button.rs
luda-editor/luda-editor-client/src/app/sequence_list/open_button.rs
namui/src/namui/manager/web/mouse_manager.rs
namui/src/namui/render/mouse_cursor.rs

Add pointer cursor

---

.editorconfig
.github/workflows/check.yml
.github/workflows/test-namui.yml
.prettierrc
namui/src/lib.rs

I added cargo checking, namui testing github action workflows.

Add cargo check and test namui workflows

---

namui/README.md

I put hwo to run unit tests for namui.

Add namui unit tests manual

---

.github/workflows/check.yml
.github/workflows/test-namui.yml

I triggered github action to run test on pull request, but I found that it's not necessary.
Because I already put 'push trigger' too, it run test on you push the commit to branch for pull request.

Remove pull_request in github action

---

namui/src/namui/draw/text.rs
namui/src/namui/render/text.rs

I restore text background rendering from comments. other text-rendering-things will be restored next time.

Support text background rendering

---

luda-editor/luda-editor-client/src/app/editor/mod.rs
namui/src/namui/common/mod.rs
namui/src/namui/event/mod.rs
namui/src/namui/manager/mock/mouse_manager.rs
namui/src/namui/manager/web/mouse_manager.rs
namui/src/namui/mod.rs
namui/src/namui/render/rendering_tree.rs

I put buttons in mouse event.
Exactly the same with web's MouseEvent.buttons. https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons

Get buttons on mouse event

---

namui/src/namui/common/mod.rs
namui/src/namui/event/mod.rs
namui/src/namui/manager/web/keyboard_manager.rs

I simply put key down event in namui.

Support KeyDown event

---

luda-editor/luda-editor-client/src/app/editor/mod.rs
luda-editor/luda-editor-client/src/app/editor/sequence_player/mod.rs
luda-editor/luda-editor-client/src/app/sequence_list/common/rounded_rectangle.rs
luda-editor/luda-editor-client/src/app/sequence_list/events.rs
luda-editor/luda-editor-client/src/app/sequence_list/list/list.rs
luda-editor/luda-editor-client/src/app/sequence_list/list/list_item.rs
luda-editor/luda-editor-client/src/app/sequence_list/list/mod.rs
luda-editor/luda-editor-client/src/app/sequence_list/list/open_button.rs
luda-editor/luda-editor-client/src/app/sequence_list/list/preview_slider.rs
luda-editor/luda-editor-client/src/app/sequence_list/mod.rs
luda-editor/luda-editor-client/src/app/sequence_list/ops/load_sequence.rs
luda-editor/luda-editor-client/src/app/sequence_list/types/mod.rs
luda-editor/luda-editor-client/src/app/sequence_list/types/sequence_load_state_map.rs
luda-editor/luda-editor-client/src/app/sequence_list/types/sequence_preview_progress_map.rs
luda-editor/luda-editor-client/src/app/types/sequence.rs

I added preview and preview slider in sequcene page.
Slider can be controlled via mouse move.

Preview sequence in sequence list page

---

luda-editor/luda-editor-client/src/app/editor/clip_editor/mod.rs
luda-editor/luda-editor-client/src/app/editor/clipboard.rs
luda-editor/luda-editor-client/src/app/editor/job/add_camera_clip.rs
luda-editor/luda-editor-client/src/app/editor/job/mod.rs
luda-editor/luda-editor-client/src/app/editor/job/move_camera_clip.rs
luda-editor/luda-editor-client/src/app/editor/mod.rs
luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/camera_track_body/mod.rs
luda-editor/luda-editor-client/src/app/types/camera_track.rs
luda-editor/luda-editor-client/src/app/types/mod.rs
luda-editor/luda-editor-client/src/app/types/sequence.rs

I implemented Copy and paste the camera clip using Ctrl+C / Ctrl+V key.
Design doc : https://docs.google.com/document/d/1STgEyNOUcEDtoDDvpdj11U_etHmRRCukLqCU53oRmRo/edit#

Copy and paste camera clip

---

luda-editor/luda-editor-client/src/app/editor/job/move_camera_clip.rs
luda-editor/luda-editor-client/src/app/editor/job/move_subtitle_clip.rs
luda-editor/luda-editor-client/src/app/editor/mod.rs
luda-editor/luda-editor-client/src/app/editor/timeline/mod.rs
luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/camera_track_body/camera_clip_body.rs
luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/camera_track_body/mod.rs
luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/subtitle_track_body/subtitle_clip_body.rs
luda-editor/luda-editor-client/src/app/types/camera_track.rs
luda-editor/luda-editor-client/src/app/types/sequence.rs

- Clip Multi-Selection (Only clips in same track can selected together)
- Shift+click
- Ctr+click
- Multiple Clip Movement
- Camera Clips
- Subtitle Clips
Design Docs : https://docs.google.com/document/d/11zl3UsbELQixHz2p833bdXWUynufCMQ9KU6ePyMSXys/edit#

Select multiple clips and move

---

.github/workflows/test-luda-editor-clinet.yml

Running luda-editor-client test in github action.
Test Screenshot

Run luda-editor-clinet test in github action

---

luda-editor/luda-editor-client/src/app/editor/mod.rs

I created shortcut key `shift-end` and `shift-home` to select multiple clips at once.
It's very similar to other tools. If you press `shift-end` key, then it selects all the clip behind of previously selected clip. vice versa for `shift-home`.
Design docs : https://docs.google.com/document/d/1umf5k9oQ-nl51LQNKtxJRHPgcLkkkTS6FPSHwu464kE/edit?usp=sharing

Select clips at once with shift home/end

---

luda-editor/luda-editor-client/src/app/editor/timeline/time_ruler/mod.rs
namui/src/namui/common/mod.rs
namui/src/namui/manager/web/mouse_manager.rs
namui/src/namui/render/rendering_tree.rs

I exposed the mouse button which make a mouse-down or mouse-up event. I need it to make context menu, without this pr, i don't know what button I pressed. I need to know the button user pressed was right button or not.

Expose mouse button that occurs mouse event

---

namui/src/namui/mod.rs
namui/src/namui/render/absolute.rs
namui/src/namui/render/mod.rs
namui/src/namui/render/rendering_tree.rs
namui/src/namui/skia/web/canvas.rs
namui/src/namui/skia/web/canvas_kit/canvas.rs
namui/src/namui/skia/web/canvas_kit/canvas_kit.rs
namui/src/namui/skia/web/canvas_kit/matrix_3x3_helpers.rs
namui/src/namui/skia/web/canvas_kit/mod.rs

Created new special rendering node, `Absolute` which can render something in absolute coordinate.

Render in absolute coordinate

---

namui/src/namui/namui_web/mod.rs

I turned off web default context menu behavior (right clicking)

Prevent web default context menu behavior

---

luda-editor/luda-editor-client/src/app/editor/context_menu/mod.rs
luda-editor/luda-editor-client/src/app/editor/events.rs
luda-editor/luda-editor-client/src/app/editor/mod.rs
luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/camera_track_body/mod.rs
luda-editor/luda-editor-client/src/app/types/sequence.rs

I created simple context menu, which has only single purpose -creating camera clip-(so the code maybe looks ugly :S )
The reason why I made a code like this is, I think it's not a good timing to make a expandable, well-made context menu right now. 
Because there are no plan to expand context menu yet. It's not a priority.
Design doc : https://docs.google.com/document/d/1RBYI4N5Blz8jCiNqReYvy-QCL0r96NqrSer5Ra4xBbs/edit?usp=sharing

Create camera clip using context menu

---

namui/src/namui/render/types.rs

I simply added is_xy_in method in XywhRect.

Support is_xy_in in XywhRect

---

luda-editor/luda-editor-client/src/app/app.rs
luda-editor/luda-editor-client/src/app/editor/mod.rs
luda-editor/luda-editor-client/src/app/editor/sequence_saver.rs
luda-editor/luda-editor-client/src/app/editor/top_bar/mod.rs
luda-editor/luda-editor-client/src/app/editor/top_bar/saving_status_text.rs
luda-editor/luda-editor-client/src/app/sequence_list/list/list_item.rs
luda-editor/luda-editor-client/src/app/sequence_list/list/open_button.rs
luda-editor/luda-editor-rpc/src/lib.rs
luda-editor/luda-editor-server/src/main.rs

I saved sequence automatically, checking the sequence changes.
I hightly recommend to read design doc before review.

Save sequence automatically

---

namui/src/namui/mod.rs
namui/src/namui/render/text.rs
namui/src/namui/skia/base/paint_builder.rs
namui/src/namui/skia/web/canvas_kit/paint.rs
namui/src/namui/skia/web/paint.rs

I fix namui to show text border.

Support text border

---

luda-editor/luda-editor-client/src/app/editor/job/move_subtitle_clip.rs
luda-editor/luda-editor-client/src/app/editor/job/sync_subtitles.rs
luda-editor/luda-editor-client/src/app/editor/job/test_utils.rs
luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/subtitle_track_body/subtitle_clip_body.rs
luda-editor/luda-editor-client/src/app/types/sequence.rs

I rendered 'Check!' text on subtitle clip if
1. it is new subtitle clip
2. it is not very new, but position moved by syncing algorithm

Show flag on subtitle clip to check to update

---

namui/src/namui/mod.rs
namui/src/namui/render/matrix.rs
namui/src/namui/render/mod.rs
namui/src/namui/render/rendering_tree.rs
namui/src/namui/render/rotate.rs
namui/src/namui/skia/web/canvas.rs
namui/src/namui/skia/web/canvas_kit/canvas.rs

I put namui::rotate to rotate rendering tree.

Rotate rendering tree

---

luda-editor/luda-editor-client/src/app/app.rs

I just removed socket logs because that logs hide other logs. I think socket logs is not important.

Remove socket log

---

luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/camera_track_body/camera_clip_body/mod.rs
luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/subtitle_track_body/subtitle_clip_body.rs
namui/src/namui/skia/base/path_builder.rs
namui/src/namui/skia/web/canvas_kit/path.rs
namui/src/namui/skia/web/path.rs

Subtitle clip would be not good for visibility so I renew it's layout.
During this changes, I updated camera clip's color and namui to support arc drawing.
Design doc : https://docs.google.com/document/d/1lXBEiRhDXzdGiQQTbLN3EWL3WGvCZazQ7v_tNzf10LI/edit#heading=h.vxdummyxmeri
I changed selected camera clip's background color.

Preview subtitle clip in timeline

---

luda-editor/luda-editor-client/src/app/types/subtitle_play_duration_measure.rs
luda-editor/resources/meta.json

I tuned subtitle play duration algorithm for Korean subtitle.

Update subtitle play duration algorithm

---

namui-cli/src/build/web_server/web_server.rs

An unknown stuck occurs in the `Bundle`.
Related issues: #70, #82
I couldn't find the definite conditions for stuck to occur. So I can't guarantee that this pr solves the above issues.
I replace `map` and `block_on` with `warp::Filter.and_then`.
This is not a common way to use async with warp. I didn't know how to use `warp::Filter.and_then` with local variables at that time. So I used trick of `map` and `block_on`.
In my case, since this modification, stuck has no longer occurred. So I made this pr for more tests.

Use and_then to serve bundle

---

luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/empty_button.rs
luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/mod.rs
luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/types.rs
luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/mod.rs
luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/wysiwyg_editor/mod.rs
luda-editor/luda-editor-client/src/app/editor/job/change_image.rs
luda-editor/luda-editor-client/src/app/editor/job/test_utils.rs
luda-editor/luda-editor-client/src/app/editor/mod.rs
luda-editor/luda-editor-client/src/app/editor/sequence_player/content_loader.rs
luda-editor/luda-editor-client/src/app/types/camera_angle.rs

- Create empty camera angle, making character_pose_emotion as Option.
- Remove `return` in editor's update function.
Design docs : https://docs.google.com/document/d/1Bg3FQmkVK2LFjZNLVtDELT0q3HkJm3NnyW0S3RfieDA/edit#

Support empty camera angle

---

namui-cli/www/hotReload.js

Simply reconnect after disconnection.
https://stackoverflow.com/questions/22431751/websocket-how-to-automatically-reconnect-after-it-dies

Reconnect to web bundle server on disconnect

---

.github/workflows/namui-test-host-linux.yml
docker-images/namui-test-host/linux.Dockerfile
namui-cli/src/main.rs
namui-cli/src/procedures/linux/wasm_unknown_web/test.rs
namui-cli/src/procedures/test/mod.rs

- Run test using docker even in the local dev environment
- To do this, I calculated path dependencies recursively for mounting to docker using bind

Test with docker

---

.github/actions/push-docker-image/action.yml

custom action cannot access to secret so i fixed it.

Fix wrong action variable

---

namui-prebuilt/src/scroll_view.rs

I found there is strange rect next of content, on right side. I removed it.

Remove scroll bar rect

---

.github/workflows/namui-test-host-linux.yml
docker-images/namui-test-host/linux.Dockerfile
namui-cfg/src/lib.rs
namui-cli/src/main.rs

Install namui-cli in namui-test-host docker image

---

.github/workflows/namui-test-host-linux.yml
docker-images/namui-test-host/linux.Dockerfile

Revert "Install namui-cli in namui-test-host docker image"

---

namui/sample/text-input/src/lib.rs
namui/src/namui/render/text_input/draw_caret.rs
namui/src/namui/render/text_input/draw_texts_divided_by_selection.rs

I forgot taking video about bug ahaha anyway it gets massy when select texts. this PR will fix that bug.
I couldn't find this bug in sample because I used left align only in sample. So I put center and right align in sample.

Fix text input align bug

---

namui/src/namui/manager/mock/text_input_manager.rs
namui/src/namui/manager/web/text_input_manager.rs
namui/src/namui/render/text_input/mod.rs

I need to get which text input is focused or not. So I exposed this api.

Expose api: Is text input focused

---

namui/src/namui/common/mod.rs
namui/src/namui/manager/web/text_input_manager.rs
namui/src/namui/render/rendering_tree/mod.rs
namui/src/namui/render/rendering_tree/visit.rs
namui/src/namui/render/text_input/draw_caret.rs
namui/src/namui/render/text_input/get_selection_on_mouse_down.rs

I found that `text input selection changing by click` doesn't work. It's because of mouse x was global, but expected local x. I fixed it.

Fix text input mouse click x locality

---

namui/src/namui/render/rendering_tree/mod.rs

I didn't call mouse_move_out event, so I put them active.

Support mouse_move_out event

---

namui/Cargo.toml
namui/src/namui/manager/web/wheel_manager.rs

I blocked ctrl+wheel zoom in browser.
Reference : https://stackoverflow.com/a/57582286

Prevent ctrl+wheel zoom

---

luda-editor/luda-editor-client/src/app/editor/mod.rs
luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/mod.rs
namui/src/namui/manager/mock/keyboard_manager.rs
namui/src/namui/manager/web/keyboard_manager.rs
namui/src/namui/render/text_input/get_selection_on_mouse_down.rs

Replace code slice with IntoIterator

---

luda-editor/luda-editor-client/src/app/editor/timeline/mod.rs
luda-editor/luda-editor-client/src/app/types/time_per_pixel.rs

Removed not useful f32 reference parameter

Remove & for f32 param

---

namui/src/namui/render/rendering_tree/mod.rs
namui/src/namui/render/special/attach_event.rs

Same with https://github.com/NamseEnt/namseent/pull/202, support mouse event too.

Add target on mouse event

---

namui-cli/src/services/rust_project_watch_service.rs

Watch `Cargo.toml` and `.namuibundle` on namui-cli Rust Project Watch Service

Watch Cargo.toml and .namuibundle

---

luda-editor/luda-editor-client/Cargo.lock
namui/Cargo.toml
namui/src/namui/common/mod.rs
namui/src/namui/fs/bundle/read_dir/bundle_dir_reader.rs
namui/src/namui/fs/init.rs
namui/src/namui/mod.rs

Show FileSystemInitError full error message

---

namui/src/namui/mod.rs
namui/src/namui/render/rendering_tree/mod.rs
namui/src/namui/render/rendering_tree/visit.rs
namui/src/namui/render/special/mod.rs
namui/src/namui/render/special/scale.rs
namui/src/namui/skia/web/canvas.rs
namui/src/namui/skia/web/canvas_kit/canvas.rs

scale? zoom? 
scale(x, y)
zoom(x, y)
which one do you prefer?
if zoom good -> will change name before merge

Scale on render

---

luda-editor/luda-editor-client/Cargo.lock
luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/browser_item.rs
luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/mod.rs
luda-editor/luda-editor-client/src/app/editor/sequence_player/content_loader.rs
luda-editor/luda-editor-client/src/app/types/camera_angle.rs
namui/Cargo.toml
namui/src/namui/fs/bundle/read_dir/make_path_dirent_list_map.rs
namui/src/namui/fs/electron/read_dir.rs
namui/src/namui/fs/types/dirent.rs
namui/src/namui/fs/types/path_like.rs
namui/src/namui/manager/mock/image_manager.rs
namui/src/namui/manager/web/image_manager.rs
namui/src/namui/mod.rs
namui/src/namui/namui_mock/fetch.rs
namui/src/namui/render/image.rs

I found that it's very difficult to set image source from bundle. So I unified bundle dirent and previous string based url into servo's url crate.

Use Url for dirent and image source

---

namui/src/namui/render/rendering_tree/mod.rs

I hid some rendering tree functions.

Hide some rendering tree functions

---

namui/src/namui/manager/web/text_input_manager.rs
namui/src/namui/mod.rs
namui/src/namui/render/matrix.rs
namui/src/namui/render/rendering_tree/mod.rs
namui/src/namui/render/rendering_tree/visit.rs

I found that local_xy doesn't work with scale. I fixed it.
Live tested with namui-animation-editor(in dev)

Fix local_xy failure with scale

---

namui/src/namui/common/mod.rs
namui/src/namui/event/mod.rs
namui/src/namui/mod.rs
namui/src/namui/namui_context/main_loop/mod.rs
namui/src/namui/namui_context/main_loop/post_update_and_render.rs
namui/src/namui/namui_context/main_loop/pre_update_and_render.rs
namui/src/namui/namui_context/mod.rs
namui/src/namui/namui_mock/mod.rs
namui/src/namui/namui_web/mod.rs

I moved namui context codes into namui_context directory.
Will open after merging https://github.com/NamseEnt/namseent/pull/228

Clean code of namui context

---

image-cropper/src/app/cropper/selection/rect_selection.rs
luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/wysiwyg_editor/character_wysiwyg_editor/cropper.rs
namui/src/namui/manager/mock/mouse_manager.rs
namui/src/namui/manager/web/mouse_manager.rs
namui/src/namui/namui_context/main_loop/mod.rs
namui/src/namui/namui_context/main_loop/post_update_and_render.rs
namui/src/namui/render/rendering_tree/mod.rs
namui/src/namui/render/special/mouse_cursor.rs

I was surprised because it was too easy to make. Tested and worked well.
That triangle.

Set renderingTree as mouse cursor

---

namui/src/namui/render/rendering_tree/mod.rs
namui/src/namui/render/rendering_tree/visit.rs
namui/src/namui/render/special/rotate.rs

I found that I calculated rotation in wrong way. fixed it.

Fix rotation angle in cw direction

---

namui/src/namui/skia/web/canvas.rs
namui/src/namui/skia/web/canvas_kit/embind_object.rs

I found that canvaskit canvas should not be delete by users. So I revert it.

Abort deleting canvaskit canvas

---

image-cropper/src/app/cropper/canvas/canvas.rs
image-cropper/src/app/cropper/canvas/event.rs
image-cropper/src/app/cropper/canvas/tool.rs

Add zoom tool.
Shortcut is 4 and Z.
Drag to right bottom will zoom in, left up will zoom out.

Add zoom tool

---

namui/src/namui/mod.rs

Related : https://github.com/NamseEnt/namseent/pull/229
I forgot exposing event

Expose KeyboardEvent

---

namui/src/namui/common/set_timeout.rs
namui/src/namui/system/time/mock.rs
namui/src/namui/system/time/mod.rs
namui/src/namui/system/time/web.rs

I failed the test that uses time system. I forgot mocking time system to run this test.
So I mocked time system.

Mock time on test

---

namui-prebuilt/src/dropdown/mod.rs
namui-prebuilt/src/lib.rs
namui/src/namui/common/types/px.rs
namui/src/namui/common/xy.rs

https://user-images.githubusercontent.com/3580430/177841607-f2185791-c92b-496d-befe-3ebd97b0e558.mp4
example
```rust
self.dropdown.render(dropdown::Props {
rect: Rect::Xywh {
x: 0.px(),
y: 0.px(),
width: props.wh.width,
height: 40.px(),
},
items: ImageInterpolation::iter().map(|interpolation| dropdown::Item {
id: interpolation.as_ref().to_string(),
text: interpolation.as_ref().to_string(),
is_selected: interpolation.as_ref().eq(line.as_ref()),
}),
visible_item_count: 0,
on_select_item: move |item_id| {
namui::event::send(Event::SelectItem {
line: ImageInterpolation::from_str(&item_id).unwrap(),
layer_id: layer_id.clone(),
point_id: point_id.clone(),
});
},
})
```

Add dropdown

---

namui-prebuilt/src/table/mod.rs

fixes #264
I put `no-clip` version of table. user can select whether they clip cell or not.

Support no-clip for table

---

image-cropper/Cargo.lock
luda-editor/luda-editor-client/Cargo.lock
namui/Cargo.toml
namui/src/namui/common/types/mod.rs
namui/src/namui/mod.rs
namui/src/namui/render/matrix.rs
namui/src/namui/render/rendering_tree/mod.rs
namui/src/namui/render/rendering_tree/visit.rs
namui/src/namui/render/special/mod.rs
namui/src/namui/render/special/transform.rs
namui/src/namui/skia/base/path_builder.rs
namui/src/namui/skia/web/canvas.rs
namui/src/namui/skia/web/path.rs

- Support transform with matrix3x3
- Improve Matrix3x3 struct using [nalgebra](https://github.com/dimforge/nalgebra)
- Remove match in RenderingTree code to make sure engine developer should handle new rendering tree type
- Save and restore draw context matrix

Transform with matrix

---

namui/Cargo.toml
namui/src/namui/mod.rs
namui/src/namui/namui_context/main_loop/mod.rs
namui/src/namui/namui_context/main_loop/post_update_and_render.rs
namui/src/namui/namui_context/main_loop/pre_update_and_render.rs
namui/src/namui/namui_context/mod.rs
namui/src/namui/render/rendering_tree/mod.rs
namui/src/namui/render/rendering_tree/visit.rs
namui/src/namui/render/special/absolute.rs
namui/src/namui/render/special/attach_event.rs
namui/src/namui/render/special/clip.rs
namui/src/namui/render/special/custom.rs
namui/src/namui/render/special/mod.rs
namui/src/namui/render/special/mouse_cursor.rs
namui/src/namui/render/special/react.rs
namui/src/namui/render/special/rotate.rs
namui/src/namui/render/special/scale.rs
namui/src/namui/render/special/transform.rs
namui/src/namui/render/special/translate.rs
namui/src/namui/render/special/with_id.rs

Design Docs :  https://docs.google.com/document/d/1hMOtoB1LuFfOE8sETs-mgKwvMxg4by8Upjp4A5vhjA4/edit#
I think it's super able to make namui with react concept.
- Usage: https://github.com/NamseEnt/namseent/commit/f5b647d3baae41ac9100215300ca5a5c9332542d#diff-11073f8c21d4ecdcd438a0f5e3b367449a3b094a2fe6e85c785cf0bd1d0295f9R44
- Implementation: https://github.com/NamseEnt/namseent/commit/f5b647d3baae41ac9100215300ca5a5c9332542d#diff-8b3e64879d2f084b8e2ddde7172e7bace8b0ed422562a7c586e391c14ff53e6eR5
https://user-images.githubusercontent.com/3580430/179523597-5b9b2dd6-155b-44e3-9f8a-54dc8348721a.mp4
It's unstable yet.

Hello react

---

namui/sample/shader/Cargo.toml
namui/sample/shader/src/lib.rs

I made a platform to display multiple shader sample using dropdown.

Add shake shader sample

---

namui/src/namui/mod.rs

I removed it when I change system.

Hook panic in console error

---

namui-cli/www/cache.js
namui-cli/www/idb-keyval.6.2.0/index.d.ts
namui-cli/www/idb-keyval.6.2.0/index.js
namui-cli/www/index.html
namui-cli/www/main.js
namui/src/namui/system/cache/mod.rs
namui/src/namui/system/mod.rs

- I made a simple cache system using indexed db.
- Actually indexed db is not cache, it's persistent db. There are no rule about cache policy or cache time-to-live yet.
- To support cache as js module, I changed wasm-pack target from `no-modules` to `web`.
Ah, I made a screenshot after run twice so the first one shows 'Some', it was 'None' on first test.

Hello cache system

---

namui-cli/src/services/rust_build_service.rs

I said I changed it in https://github.com/NamseEnt/namseent/pull/291 but I forgot to save the file. sorry.

Change wasm-pack target from 'no-modules' to 'web'

---

namui-cli/www/index.html

I found that I removed hotReload from index.html.
https://github.com/NamseEnt/namseent/pull/291/files#diff-6466053d09e2dd03b9eeac39876ec1a43b9ac4b095a87354f1fb3930863e3f01L22

Restore hotReload.js

---

image-cropper/Cargo.lock
luda-editor/luda-editor-client/Cargo.lock
namui/Cargo.toml
namui/src/namui/common/types/time.rs
namui/src/namui/system/time/mod.rs

I put delay fn in time system.

Support delay

---

namui/Cargo.toml
namui/src/namui/system/file/dialog/mod.rs
namui/src/namui/system/file/mod.rs

I implemented file open dialog.
https://user-images.githubusercontent.com/3580430/184634775-e10b2f4c-5448-49bf-81de-b0b79ce87889.mp4

Hello file dialog!

---

image-cropper/Cargo.lock
image-cropper/src/app/cropper/render_back_button.rs
image-cropper/src/app/cropper/render_save_button.rs
image-cropper/src/app/file_selector/render_file_select_dialog_open_button.rs
luda-editor/client/Cargo.lock
luda-editor/client/src/pages/sequence_edit_page/loaded/components/timeline/render/time_ruler/time_text.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/render/line_list.rs
luda-editor/client/src/pages/sequence_list_page/rename_modal.rs
namui-animation-editor/src/dial_counter/mod.rs
namui-animation-editor/src/layer_list_window/body.rs
namui-animation-editor/src/layer_list_window/header.rs
namui-animation-editor/src/time_ruler/time_text.rs
namui-prebuilt/src/center_text.rs
namui-prebuilt/src/typography.rs
namui/Cargo.toml
namui/sample/multiline-text/src/lib.rs
namui/sample/text-input/src/lib.rs
namui/src/namui/draw/text/mod.rs
namui/src/namui/draw/text/text_wrap.rs
namui/src/namui/render/text.rs

- I implemented word wrap multiline text with https://crates.io/crates/textwrap.
_

Render multiline text with word warp

---

luda-editor/client/.gitignore

I forgot remove setting.json from project directory.

Ignore setting.json for git

---

namui-animation-editor/src/time_point_editor/wysiwyg_window/update/dragging/mod.rs
namui/sample/shader/src/lib.rs
namui/src/namui/animation/animatable_image.rs
namui/src/namui/draw/image.rs
namui/src/namui/render/image.rs
namui/src/namui/system/file/picker/mod.rs
namui/src/namui/system/image.rs

- I made image from user picked file

Show image from file

---

namui/src/namui/render/text_input/draw_caret.rs
namui/src/namui/render/text_input/draw_texts_divided_by_selection.rs
namui/src/namui/render/text_input/mod.rs

- Update selection if text input's props.text changed.
Idea from react-dom https://github.com/facebook/react/blob/e099e1dc0eeaef7ef1cb2b6430533b2e962f80a9/packages/react-dom/src/client/ReactInputSelection.js#L190

Handle text change exception for text input

---

namui-prebuilt/src/button.rs

`text_button_fit` makes width-fit button using bounding box.

Support width-fit button

---

namui-prebuilt/src/table/mod.rs

Support fit and padding
- fit
- It makes fixed cell using rendering tree's bounding_box. Also support horizontal/vertical alignment by container.
- For example, if container is horizontal, it will align vertically.
- padding
- It just simply makes padding inside of cell.

Add table fit and padding

---

luda-editor/server/src/services/project/mod.rs

I found the wrong id setting for project shared data.

Match project shared data id with project id

---

namui/src/namui/common/types/macros.rs
namui/src/namui/common/types/one_zero.rs
namui/src/namui/common/types/percent.rs
namui/src/namui/common/types/px.rs

I add macro to support adding `PxExt` things easily.

Support Ext using macro

---

namui/src/namui/render/image.rs

ImageFit is very confusing me every time because I don't get what result will be. So I put comment about it, from mdn's documentation.

Explain ImageFit

---

namui/src/namui/skia/base/paint_builder.rs
namui/src/namui/skia/web/color_filter.rs

Replace reference to copy for simple struct

---

luda-editor/server/src/services/sequence/mod.rs

I found the same issue with https://github.com/NamseEnt/namseent/pull/351 but for sequence.
I searched all code with `Uuid::new_v4` to make sure whether other code is find or not.

Fix wrong sequence id matching

---

luda-editor/server/clear-storage.sh
luda-editor/server/run_local_storage.sh

I hate docker doesn't install compose v2 automatically

Use docker-cli, not docker compose v2

---

cargo-clean-check-fmt-all.py

Sometime cargo check makes error. cargo clean fixed that problem a lot of times so I made a new script for that.

Add script to clean and check all

---

namui-prebuilt/src/list_view.rs

Before
https://user-images.githubusercontent.com/3580430/193466142-72799933-19a0-4464-8bbb-779f8308e0c2.mp4
After
https://user-images.githubusercontent.com/3580430/193466212-5a2a7f6e-9b16-4962-b0ee-8e68dad53e2a.mp4

Limit maximum scroll y

---

luda-editor/client/src/pages/sequence_edit_page/loaded/render/line_list/mod.rs

Add border for Line List header

---

luda-editor/client/src/components/context_menu.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/mod.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/update/mod.rs

1. Block clicking context menu item on right click
2. Close context menu when click outside
https://user-images.githubusercontent.com/3580430/193591143-f50dbac8-7f90-472e-8f4f-c1a564b05763.mp4

Close context menu on click outside

---

luda-editor/client/src/components/sequence_player.rs

- Keep text on transition
- Keep image if transition images
- Change text opacity during transition
Before
https://user-images.githubusercontent.com/3580430/194013282-23c8122c-605c-43b0-a75d-2e41f4d0a7d6.mp4
After
https://user-images.githubusercontent.com/3580430/194013309-0e141cb1-ca41-42d3-bc0f-3b1f91a3976e.mp4

Enhance transition effect

---

namui/src/namui/mod.rs
namui/src/namui/system/text_input/mod.rs

Support text_input blur

---

luda-editor/client/src/pages/sequence_list_page/mod.rs
luda-editor/rpc/src/lib.rs
luda-editor/server/delete_dynamodb_item.sh
luda-editor/server/src/main.rs
luda-editor/server/src/services/sequence/mod.rs
luda-editor/server/src/storage/dynamo_db/singular.rs
luda-editor/server/src/storage/s3/mod.rs

- Rename Sequence
- Delete Sequence
- Remove allow(dead_code) flag
Tested in local.
Copilot did more than half for me. good ai

Rename and delete sequence

---

namui-prebuilt/src/scroll_view.rs
namui/src/namui/common/types/macros.rs

Before
https://user-images.githubusercontent.com/3580430/198869566-60d0d1f8-f54d-4a0b-b085-cb487677064f.mp4
After
https://user-images.githubusercontent.com/3580430/198869572-880814f1-86e5-42f6-90e7-99ae90a7a773.mp4

Floor scroll-y to prevent alias flickering

---

.github/workflows/namui-test-host-linux.yml
namui/sample/rect/.cargo/config.toml
namui/sample/rect/.gitignore
namui/sample/rect/Cargo.toml
namui/sample/rect/src/lib.rs
namui/src/namui/render/rect.rs

We calculated rect's storke position in wrong way because we misunderstood about skia's coordinate.
So I make it fix with some comment.
Screenshot of sample

Fix wrong rect border stroke

---

luda-editor/client/src/lib.rs
luda-editor/client/src/viewer/mod.rs

I add simple viewer using url like `{luda-editor url}/index.html?view&sequence_id={id}`.

Add viewer

---

luda-editor/client/src/components/sequence_player.rs

Tested in local dev env
Super convenient

Move preview cut using arrow left-right

---

luda-editor/client/src/components/sequence_player.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/mod.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/update/mod.rs
luda-editor/client/src/viewer/mod.rs

Start preview from cut of context menu

---

luda-editor/client/src/pages/sequence_edit_page/loaded/mod.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/update/mod.rs
luda-editor/rpc/src/data.rs

Copy-cut-paste cut using context_menu

---

namui-prebuilt/src/scroll_view.rs
namui/src/namui/render/rendering_tree/mod.rs
namui/src/namui/render/special/attach_event.rs

closes https://github.com/NamseEnt/namseent/issues/339
Before
https://user-images.githubusercontent.com/3580430/201351893-021d8f1d-2211-4365-a05c-b4ead5c228a1.mp4
After
https://user-images.githubusercontent.com/3580430/201351878-e239db7f-4e64-44ff-8579-2bb3c047a1c2.mp4

Stop wheel event propagation on list view wheel

---

namui-cli/www/canvaskit-wasm/canvaskit.js

Related : https://github.com/google/skia/pull/106
I patched Canvaskit issue manually. This fix the problem.
https://user-images.githubusercontent.com/3580430/201613749-7b4982c5-2368-4c74-a03f-bbbd8af704af.mp4

Patch canvaskit temporally

---

luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/image_filter.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/mod.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/render/filtered_image_list.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/update/mod.rs
namui-prebuilt/src/list_view.rs

1. [Move image list using arrow key](https://github.com/NamseEnt/namseent/commit/902bc1b228d7c3231b5cd51993dda09dc608bbbf)
2. [Scroll to moved](https://github.com/NamseEnt/namseent/commit/6da366282c2c7138b9767149d4bd60d414a582d8)
https://user-images.githubusercontent.com/3580430/201707590-3e6a8e20-ad89-4b87-9f0f-812e54b3c9d9.mp4

Move image list using arrow key

---

luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_table/mod.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_table/render/mod.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_table/render/row.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_table/update/mod.rs

Changes
1. Drag by mouse
2. Esc to reset dragging and editing labels
No functionality for dragging yet. I will make copy and paste labels using this.
https://user-images.githubusercontent.com/3580430/202728411-f180bcd3-4003-4ccb-9bfa-bc928517ab4d.mp4

Drag cells

---

namui-prebuilt/src/lib.rs
namui-prebuilt/src/vh_list_view.rs

`vh_list_view` is very same with `list_view`, but it can have various height items unlike `list_view` which have fixed, single height.
I made this for Sheet (#456).
https://github.com/NamseEnt/namseent/blob/58a6fc65f1fef0efecc262f7b5cfb80c96bca3f9/namui-prebuilt/src/sheet/render/mod.rs#L45-L52

Hello vh_list_view!

---

luda-editor/client/src/components/context_menu.rs
namui-prebuilt/src/vh_list_view.rs

#459 and #458 merged even it has warning and error on build.
I will fix catching build error and warning with https://github.com/NamseEnt/namseent/pull/460.
Before it, I need to merge this first to make it right.
This PR only fix that error and warning.

Fix wrong code with #459 and #458 prs

---

luda-editor/client/src/pages/sequence_edit_page/loaded/update/mod.rs

Simple changes, better ux. It bother me so I needed simple unicode sign to easily check which menu I wanted to use.

Add arrow sign for 'Insert Cut'

---

.github/ISSUE_TEMPLATE/image-request.yml
luda-editor/client/src/pages/sequence_edit_page/loaded/mod.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/update/copy_issue_info.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/update/mod.rs
namui/src/namui/system/clipboard/mod.rs
namui/src/namui/system/mod.rs

https://user-images.githubusercontent.com/3580430/204091199-994d2e39-066c-45c7-a31c-40eca6f15d74.mp4
1. Add issue template for image request to takiki
2. namui supports clipboard copy
3. luda-editor supports copy issue info using context menu
You can test issue template at here https://github.com/namse/issue-template-test/issues , try making new issue.

Copy issue info to clipboard

---

luda-editor/client/src/pages/sequence_edit_page/loaded/components/wysiwyg_editor/render/mod.rs

closes #448 
Super FANCY and useful

Render grid guide for wysiwyg editor

---

luda-editor/client/src/lib.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/mod.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/update/mod.rs
luda-editor/client/src/share_preview.rs
luda-editor/client/src/viewer/mod.rs

This PR makes context menu item for copying preview link to share.
local tested.

Copy preview link

---

.github/actions/namui-test/action.yml
docker-images/namui-test-host/linux.Dockerfile
image-cropper/Cargo.lock
image-cropper/Cargo.toml
luda-adventure/Cargo.lock
luda-editor/client/Cargo.lock
luda-editor/lambda-web/Cargo.lock
luda-editor/server/Cargo.lock
namui-animation-editor/Cargo.toml
namui-animation-editor/sample/Cargo.toml
namui-cli/Cargo.lock
namui-cli/src/procedures/linux/wasm_unknown_web/test.rs
namui/sample/image-load-background/Cargo.toml
namui/sample/multiline-text/Cargo.toml
namui/sample/rect/Cargo.toml
namui/sample/shader/Cargo.toml
namui/sample/text-input/Cargo.toml
namui/sample/type_macro/Cargo.toml

Update rust from `1.64` to `1.65`

Update rust version

---

luda-adventure/.vscode/settings.json
luda-adventure/src/app/game/game.rs
luda-adventure/src/app/game/interaction/event.rs
luda-adventure/src/app/game/interaction/get_interactive_object_list.rs
luda-adventure/src/app/game/interaction/mod.rs
luda-adventure/src/app/game/interaction/nearest_entity_id.rs
luda-adventure/src/app/game/known_id/object.rs
luda-adventure/src/app/game/mod.rs
luda-adventure/src/app/game/render/create_rendering_context.rs
luda-adventure/src/app/game/render/mod.rs
luda-adventure/src/app/game/render/render_interaction_guide.rs
luda-adventure/src/app/game/types/game_state/tick_state.rs
luda-adventure/src/app/game/update/handle_interaction.rs
luda-adventure/src/app/game/update/mod.rs
luda-adventure/src/component/interactor.rs
luda-adventure/src/component/mod.rs

- Freezing when font is first rendered.

Handle user interaction for entity

---

luda-adventure/src/app/game/render/render_interaction_guide.rs

Respond for [#476(comment)](https://github.com/NamseEnt/namseent/pull/476#discussion_r1039944616)

Do not change font_type.size

---

namui/src/namui/system/image.rs

Just call `try_load_url()` repeatedly until loaded.

Add image url loading function

---

namui/src/namui/system/typeface/load_sans_typeface_of_all_languages.rs

Cache fonts explicitly with `namui::cache`.

Try fetch font from cache first

---

namui-animation-editor/src/time_point_editor/line_edit_window/render/mod.rs
namui-prebuilt/src/dropdown/mod.rs
namui/sample/shader/src/lib.rs

Previously I checked selection by id of items and it makes code very complicated, so I removed and just passed same shape of closure for every items.

Remove id for dropdown item for easy callback

---

namui/src/namui/draw/text.rs
namui/src/namui/render/text.rs
namui/src/namui/render/text_input/draw_texts_divided_by_selection.rs
namui/src/namui/render/text_input/mod.rs
namui/src/namui/skia/types.rs
namui/src/namui/skia/web/canvas.rs
namui/src/namui/skia/web/canvas_kit/canvas.rs

Add underline

---

namui/sample/tab-to-next-text-input/.cargo/config.toml
namui/sample/tab-to-next-text-input/.gitignore
namui/sample/tab-to-next-text-input/Cargo.toml
namui/sample/tab-to-next-text-input/src/lib.rs

https://user-images.githubusercontent.com/3580430/220003711-1f867de3-263b-45b4-a846-da89d8a6ac16.mp4

Add namui sample for `Tab to next text input sample`

---

luda-editor/server/document-macro/src/lib.rs
luda-editor/server/server-core/src/lib.rs
luda-editor/server/server-core/src/services/project/mod.rs
luda-editor/server/server-core/src/services/sequence/mod.rs
luda-editor/server/server-core/src/storage/dynamo_db/singular.rs
luda-editor/server/server-core/src/storage/dynamo_db/transact.rs

Previously I changed server code to use macro instead of direct db change call, but function `update` didn't applied. That made errors on update call. So I changed it to use macro.

Change db update with macro

---

luda-adventure/src/app/game/game.rs
luda-adventure/src/app/game/image_loader.rs
luda-adventure/src/app/game/map/map_loader.rs
luda-adventure/src/app/game/menu/event.rs
luda-adventure/src/app/game/menu/menu.rs
luda-adventure/src/app/game/menu/mod.rs
luda-adventure/src/app/game/menu/render/render_in_game_menu.rs
luda-adventure/src/app/game/menu/render/render_start_menu.rs
luda-adventure/src/app/game/mod.rs
luda-adventure/src/app/game/save_load.rs
luda-adventure/src/app/game/types/game_state/camera_state.rs
luda-adventure/src/app/game/types/game_state/game_state.rs
luda-adventure/src/app/game/types/game_state/quest/quest_state.rs
luda-adventure/src/app/game/types/game_state/tick_state.rs
luda-adventure/src/app/game/update/set_character_movement_according_to_user_input.rs

- Try auto save every 5 seconds.

Save and load game automatically

---

namui/src/namui/system/keyboard.rs

https://namseent.zulipchat.com/#narrow/stream/332914-.EA.B8.B0.EC.88.A0.EC.97.B0.EA.B5.AC.EC.86.8C/topic/.E2.9C.94.20f12.26f5

Prevent prevent_default for devtool or refresh

---

luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_edit_modal/mod.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_upload/mod.rs
namui/Cargo.toml
namui/src/namui/common/file.rs
namui/src/namui/common/mod.rs
namui/src/namui/event/mod.rs
namui/src/namui/namui_context/main_loop/post_update_and_render.rs
namui/src/namui/namui_context/main_loop/pre_update_and_render.rs
namui/src/namui/render/image.rs
namui/src/namui/render/rendering_tree/mod.rs
namui/src/namui/render/special/attach_event.rs
namui/src/namui/system/drag_and_drop/mod.rs
namui/src/namui/system/file/picker/mod.rs
namui/src/namui/system/image.rs
namui/src/namui/system/keyboard.rs
namui/src/namui/system/mod.rs

- Support drop the file using HTML Drop event https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drop_event
- Move `File` struct from file system to namui common
Local Tested

Support drop the file

---

.github/workflows/destory-luda-editor.yml

This need to be tested. Let's DO IT

Destory luda editor when branch destroyed

---

luda-editor/client/src/pages/project_list_page/mod.rs
namui/src/namui/system/clipboard/mod.rs
namui/src/namui/system/image.rs

https://user-images.githubusercontent.com/3580430/221488146-2876a192-b3f3-4948-a5d4-4ad700b6c7e0.mp4
```rust
.attach_event(|build| {
build.on_mouse_down_in(|_event| {
namui::log!("mouse down in");
spawn_local(async move {
let result = namui::clipboard::read_images().await;
namui::log!("clipboard result: {:?}", result);
let Ok(images) = result else {
return;
};
if images.is_empty() {
return;
}
namui::event::send(Event::ImageLoaded {
image: images.first().unwrap().clone(),
})
})
});
})
```
https://user-images.githubusercontent.com/3580430/221492810-422199d9-e93f-4b76-864f-98794ad9abcd.mp4

Read images from clipboard

---

.github/workflows/deploy-luda-editor.yml
.github/workflows/destory-luda-editor.yml

tested: https://github.com/NamseEnt/namseent/actions/runs/4279782373/jobs/7450837127
prev wrong pr: https://github.com/NamseEnt/namseent/pull/515

Fix wrong luda-editor destory script

---

namui/src/namui/system/clipboard/mod.rs

It's necessary to upload image file to server.

Support clipboard image buffer

---

namui-prebuilt/src/lib.rs
namui-prebuilt/src/simple_rect.rs
namui-prebuilt/src/table/mod.rs
namui-prebuilt/src/typography/body.rs

1. `fn transparent_rect`
2. padding for table, vertical and horizontal manually
3. body/center_top typography

prebuilt: Add functions

---

namui/src/namui/mod.rs

lazy_static is very common, so I decided to export it from namui to namui user.

Export lazy_static

---

namui-cli/Cargo.lock
namui-cli/Cargo.toml
namui-cli/build.rs
namui-cli/scripts/install.sh
namui-cli/scripts/uninstall.sh
namui-cli/src/cli.rs
namui-cli/src/main.rs
namui-cli/src/services/electron_package_service.rs

Complete arg of namui cli automatically

---

luda-editor/server/server-core/src/services/image/documents.rs
luda-editor/server/server-core/src/storage/s3/mod.rs
luda-editor/server/server-core/src/storage/s3/presigned_url.rs

s3.rs is too big, so I divide presigned-url into separated file.

Separate presigned url code

---

luda-editor/client/src/pages/sequence_edit_page/loaded/components/character_editor/render/part_picker.rs
luda-editor/rpc/src/data/cg.rs
luda-editor/server/server-core/src/services/cg/mod.rs
luda-editor/server/server-core/src/services/cg/parse_psd_to_inter_cg_parts.rs
luda-editor/server/server-core/src/services/cg/psd_to_cg_file.rs

- Support folder variation
- Add always-on part

Fix parsing of psd to cg

---

.github/workflows/namui-test-host-linux.yml
luda-editor/server/document-macro/src/lib.rs
luda-editor/server/run_test.sh
luda-editor/server/server-bin/Cargo.lock
luda-editor/server/server-core/Cargo.lock
luda-editor/server/server-core/Cargo.toml
luda-editor/server/server-core/src/lib.rs
luda-editor/server/server-core/src/services/cg/mod.rs
luda-editor/server/server-core/src/services/image/mod.rs
luda-editor/server/server-core/src/services/memo/mod.rs
luda-editor/server/server-core/src/services/project/mod.rs
luda-editor/server/server-core/src/services/sequence/mod.rs
luda-editor/server/server-core/src/storage/dynamo_db/singular.rs
luda-editor/server/server-dev-cli/Cargo.lock

and add anyhow in luda-editor server

Support query pagination

---

luda-editor/client/src/components/sequence_player.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/components/character_editor/render/part_picker.rs
luda-editor/client/src/pages/sequence_edit_page/loaded/components/wysiwyg_editor/render/mod.rs
luda-editor/rpc/src/data/mod.rs

- Fix cg part variants to be rendered from last
- first item of part_variants will be render on top

Fix cg part priority

---

.github/actions/init-test-job/action.yml
docker-images/namui-test-host/linux.Dockerfile

Wasm-pack team doesn't publish updates so I put wasm-pack's specific version.
https://github.com/rustwasm/wasm-pack/pull/1305

Set Wasm-pack 0.11.1

---

cargo-fix-fmt-all.py

Add --broken-code

---

luda-editor/migration/migration-macro/Cargo.lock
luda-editor/rpc/src/data/cut/previous/v1.rs

FYI: [bincode spec sheet](https://github.com/bincode-org/bincode/blob/trunk/docs/spec.md)

Fix tests for serde with migration

---

namui/src/namui/skia/base/paint_builder.rs
namui/src/namui/skia/web/canvas_kit/paint.rs
namui/src/namui/skia/web/paint.rs

Set paint's `BlendMode` with `PaintBuilder::set_blend_mode();`

Enable setBlendMode function of Paint

---

.github/workflows/publish-extension.yml
extension/README.md
extension/package-lock.json
extension/package.json
extension/snippets.code-snippets

https://github.com/NamseEnt/namseent/assets/3580430/65de1292-6645-4e8d-be33-9d282c9a60f4

Extension 0.0.2 - Component code snippet

---

.github/workflows/publish-extension.yml

Fuck! `on create:` doesn't work for tags!

Keep use on-push for tags

---

extension/README.md
extension/in_rust/src/lib.rs
extension/in_rust/src/wrap_code_with_block.rs
extension/package.json
extension/src/extension.ts

Add quick fix action wrapping code in block

---

luda-editor/server/server-bin/Cargo.lock
luda-editor/server/server-core/Cargo.lock
luda-editor/server/server-core/Cargo.toml
luda-editor/server/server-core/src/services/cg/layer_tree.rs
luda-editor/server/server-core/src/services/cg/psd_to_cg_file.rs
luda-editor/server/server-dev-cli/Cargo.lock

Fix 596
Replaced some for loops with rayon for multi-thread

Optimize complete_put_psd with rayon

---

namui-cli/src/procedures/linux/wasm_unknown_web/build.rs
namui-cli/src/services/drawer_watch_build_service.rs
namui-cli/src/services/resource_collect_service.rs

namui-cli doesn't collect drawer bundle. Tested in local

Collect drawer into build artifact

---

.github/workflows/publish-extension.yml

Current workflow code doesn't get tags so it fail to check whether tag exists or not.

Check tag exists with deep checkout

---

namui/src/namui/render/text_input/mod.rs

Change mouse pointer for text_input

---

namui-cli/src/services/drawer_watch_build_service.rs
namui-cli/src/services/wasm_bundle_web_server.rs
namui-cli/src/services/wasm_watch_build_service.rs
namui-cli/src/services/wasm_web_runtime_watch_build_service.rs
namui-cli/src/types.rs
namui-cli/webCode/src/hotReload.ts

Show build sign on screen during build

---

luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/graphic_clip.rs
luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/mod.rs
namui/src/namui/hooks/key.rs

Render screen graphics with key

---

luda-editor/client/src/pages/sequence_edit_page/components/cut_editor/background_with_event.rs
luda-editor/server/server-core/src/services/sequence/documents.rs
luda-editor/server/server-core/src/services/sequence/mod.rs

Closes https://github.com/NamseEnt/namseent/issues/638
- Bind ctrl+z, ctrl+y, ctrl+shift+z key for undo-redo
- Fix server error

Add undo-redo, Fix wrong index calculation

---

luda-editor/client/Cargo.lock
luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/graphic_clip.rs
luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/wysiwyg_tool.rs
luda-editor/rpc/Cargo.lock
namui-cli/webCode/src/main/main.ts
namui-cli/webCode/src/worker.ts
namui-drawer/Cargo.lock
namui-drawer/Cargo.toml
namui-drawer/src/lib.rs
namui-drawer/src/load_image.rs
namui-prebuilt/Cargo.lock
namui/Cargo.lock
namui/sample/image-load-background/Cargo.lock
skia/canvas-kit-wasm-bindgen/src/image.rs
skia/skia/Cargo.lock
skia/skia/Cargo.toml
skia/skia/src/canvas_kit/ck_skia.rs
skia/skia/src/canvas_kit/image.rs
skia/skia/src/traits.rs

closes https://github.com/NamseEnt/namseent/issues/644, https://github.com/NamseEnt/namseent/issues/645
- Delete with del key
- Copy with ctrl+c key, fixing some namui-drawer problems

Key binding - ctrl+c, del

---

.github/workflows/cargo-lock-update.yml
for-all-projects/Cargo.lock
for-all-projects/Cargo.toml

Use pat to trigger workflow

---

luda-editor/client/src/components/sequence_player.rs

Block mouse event on text box background

---

.github/workflows/all.yml
extension/in_rust/src/wrap_code_with_block.rs
for-all-projects/Cargo.lock
for-all-projects/Cargo.toml
for-all-projects/build.rs
for-all-projects/src/cli.rs
for-all-projects/src/run_commands.rs
namui-drawer/src/lib.rs

1. clippy --fix doesn't throw error even it fail to fix
2. they said completion script will work if it placed to ~/.local/share/bash-completion/completions

Divide clippy and clippy-fix

---

luda-editor/client/src/pages/project_list_page/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/character_editor/cg_picker.rs
luda-editor/client/src/pages/sequence_edit_page/components/character_editor/part_picker.rs
luda-editor/client/src/pages/sequence_edit_page/components/cut_list_view/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/image_picker/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/memo_list_view/mod.rs
luda-editor/client/src/pages/sequence_list_page/mod.rs
namui-prebuilt/src/dropdown/mod.rs
namui-prebuilt/src/list_view.rs
namui-prebuilt/src/scroll_view.rs
namui-prebuilt/src/table/hooks.rs
namui-prebuilt/src/vh_list_view.rs
namui/src/namui/hooks/ctx/render_ctx/compose_ctx/mod.rs
namui/src/namui/hooks/ctx/render_ctx/mod.rs
namui/src/namui/hooks/ctx/render_ctx/public.rs
namui/src/namui/hooks/ctx/render_ctx/renderer.rs
namui/src/namui/hooks/ctx/tree_ctx.rs
namui/src/namui/hooks/native/event.rs

Closes #636 
Concept of ghost rendering is little bit difficult.
I changed it to get option to handle event or not.

Fix ghost render - bounding box change

---

.github/workflows/publish-for-all-projects.yml

Fix wrong cache key

---

luda-editor/client/src/clipboard.rs
luda-editor/client/src/lib.rs
luda-editor/client/src/pages/sequence_edit_page/components/cut_editor/background_with_event.rs
luda-editor/client/src/pages/sequence_edit_page/components/cut_list_view/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/graphic_clip.rs

- Copy and paste cut on cut list
- Use trait for copying custom data to reduce human error while typing clipboard type name.
Closes #660

Copy and paste cut

---

luda-editor/client/src/pages/sequence_edit_page/atom/focused_component.rs
luda-editor/client/src/pages/sequence_edit_page/atom/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/cut_editor/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/mover.rs
luda-editor/client/src/pages/sequence_edit_page/loaded.rs

Move graphic with keyboard

---

luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/change_graphic_order.rs
luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/mod.rs

Review please
I didn't test for this code so you need to try test before use this code.

Suggestion for luda-editor/graphic-order-shortcut

---

luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/change_graphic_order.rs
luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/mod.rs

Change graphic order with shorcut

---

luda-editor/client/src/pages/sequence_edit_page/components/cut_editor/mod.rs
luda-editor/client/src/pages/sequence_edit_page/sequence/mod.rs
luda-editor/rpc/src/data/sequence_update_action.rs
luda-editor/server/server-core/src/apis/sequence/update_sequence.rs

Split cut text with shortcut

---

luda-editor/client/src/components/sequence_player.rs
luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/graphic_clip.rs
luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/rotator.rs
luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/wysiwyg_tool.rs
luda-editor/rpc/src/data/cut/previous/v2.rs
luda-editor/rpc/src/data/cut/previous/v3.rs
luda-editor/rpc/src/data/cut/previous/v4.rs
luda-editor/rpc/src/data/cut/v5.rs
luda-editor/rpc/src/data/cut_update_action.rs
luda-editor/rpc/src/data/mod.rs
luda-editor/rpc/src/data/screen_graphic/mod.rs
luda-editor/rpc/src/data/screen_graphic/previous/mod.rs
luda-editor/rpc/src/data/screen_graphic/previous/v0.rs
luda-editor/rpc/src/data/screen_graphic/v1.rs
namui-type/src/types/render/rendering_tree/special/mouse_cursor.rs
namui/src/namui/hooks/ctx/render_ctx/compose_ctx/lazy_rendering_tree.rs
namui/src/namui/hooks/ctx/render_ctx/compose_ctx/nesting.rs
namui/src/namui/hooks/ctx/render_ctx/mod.rs
namui/src/namui/hooks/ctx/render_ctx/public.rs

- LudaEditor
- Add rotation property
- Add rotator tool
- Namui
- 2c06706 Add crosshair cursor
- 76e26145bc931da6a94f92f6c5da501e00cf695b Rotate with ctx
- 53d84e5eb7219ae31bf48766ce1ef380761d6539 Get global_xy from local_xy with ctx
Closes #691

Rotate graphic with wysiwyg

---

luda-editor/client/src/components/context_menu.rs

Fix context menu divider

---

luda-editor/client/src/pages/sequence_edit_page/components/cut_list_view/cut_cell.rs
luda-editor/client/src/pages/sequence_edit_page/components/cut_list_view/mod.rs
luda-editor/client/src/pages/sequence_edit_page/loaded.rs

Render cut thumbnail

---

luda-editor/client/src/app/notification/components/copy_button.rs
luda-editor/client/src/app/notification/components/mod.rs
luda-editor/client/src/app/notification/components/notification_root.rs
luda-editor/client/src/app/notification/mod.rs
luda-editor/client/src/components/name_quick_slot.rs
luda-editor/client/src/pages/graphic_asset_manage_page/mod.rs
luda-editor/client/src/pages/graphic_asset_manage_page/upload_asset.rs
luda-editor/client/src/pages/project_acl_manage_page/mod.rs
luda-editor/client/src/pages/project_list_page/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/cut_editor/background_with_event.rs
luda-editor/client/src/pages/sequence_edit_page/components/cut_list_view/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/graphic_clip.rs

Improve notification 

---

luda-editor/cdk/lib/cdk-stack.ts
luda-editor/server/server-core/src/handle/mod.rs

https://github.com/NamseEnt/namseent/issues/697#issuecomment-1787408716
Closes #697

Increase time, memory limit for complete_psd

---

luda-editor/client/src/pages/graphic_asset_manage_page/cg_viewer/mod.rs
luda-editor/client/src/pages/graphic_asset_manage_page/image_viewer.rs
luda-editor/client/src/pages/graphic_asset_manage_page/top_bar.rs
luda-editor/client/src/pages/project_acl_manage_page/mod.rs
luda-editor/client/src/pages/project_acl_manage_page/top_bar.rs
luda-editor/client/src/pages/project_list_page/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/memo_editor/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/memo_list_view/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/name_quick_slot_modal/mod.rs
luda-editor/client/src/pages/sequence_edit_page/components/side_bar/mod.rs
luda-editor/client/src/pages/sequence_list_page/mod.rs
luda-editor/client/src/pages/sequence_list_page/rename_modal.rs
namui-prebuilt/src/button.rs

Stop using boxed event on buttons

---

x86_64-pc-windows.code-workspace.example

Build script has different command system so I override it too

Update rust-analyzer command for build script

---

namui/namui-prebuilt/Cargo.lock
namui/namui/Cargo.lock
namui/namui/Cargo.toml
namui/namui/src/namui/system/media/audio_context.rs
namui/namui/src/namui/system/media/audio_handle.rs
namui/namui/src/namui/system/media/media_handle.rs
namui/namui/src/namui/system/media/media_struct.rs
namui/namui/src/namui/system/media/mod.rs
namui/namui/src/namui/system/media/ref_counting.rs
namui/namui/src/namui/system/media/synced_audio.rs
namui/namui/src/namui/system/mod.rs
namui/sample/media/Cargo.lock
namui/sample/media/src/lib.rs

Cpal has accumulating delay problem so I removed it and used wasapi directly.
Current implementation isn't ideal for latency but it has enough low latency, 3000 bytes.
I'm going to re-implement this with wasapi IAudioClient3 for more low latency later.
One big change is that `play` function get instant to sync video and audio sync.
```rust
// prev
video_mp4.play();
// now
video_mp4.play(namui::time::now());
```

Remove cpal, Fix audio sync problem

---

namui/namui-type/src/types/units/time/duration.rs

Fix Per<Px, Duration> * Duration negative problem

---

namui/namui/src/namui/system/media/audio_buffer.rs
namui/namui/src/namui/system/media/media_core.rs
namui/namui/src/namui/system/media/media_decoding_stream.rs
namui/namui/src/namui/system/media/media_decoding_thread.rs
namui/namui/src/namui/system/media/media_handle.rs
namui/namui/src/namui/system/media/video_framer.rs
namui/sample/media/src/lib.rs

Clean code + waiting for media preload.
Check sample to check how to use it

Wait for media preload

---

namui/namui/src/namui/system/media/core/media_decoding_thread.rs

Disconnection of mpsc channel was the reason why clone-play for play and forget doesn't work.
I fixed it to keep play even channel dropped unless user stop or pause media before drop.
closes #753

Fix play and forget

---

namui/namui/src/namui/hooks/component.rs

I guess I forget removing this before

Remove unused Component fn

---

namui/skia/skia/src/native/native_skia.rs

Disable `DXGI_CREATE_FACTORY_DEBUG` flag

---

namui/namui-cli/Cargo.lock
namui/namui-cli/Cargo.toml
namui/namui-cli/src/services/runtime_project/wasm.rs
namui/namui-cli/src/services/runtime_project/x86_64_pc_windows_msvc.rs
namui/namui-cli/src/util/recreate_dir_all.rs

Previous PR deleted target directory. This PR Keeps target directory for better build speed

Keep target directory for build speed

---

namui/namui/src/namui/system/media/audio/full_load_once_audio.rs

fixes #769
https://github.com/NamseEnt/namseent/assets/3580430/dfce4bb0-88da-4df9-8c4e-b05367679375

Slice audio by channels

---

namui/namui/src/namui/hooks/ctx/render_ctx/public.rs

It made unnecessary cpu usage.

Turn off debug_bounding_box

---

luda-editor/server/document-macro/src/lib.rs

Sometime I want to save single item per document. it's useful to save configuration.

Support non-pk document

---

namui/namui/src/namui/hooks/component.rs

namui::text(), image(), path() will be deleted later. let's use struct instead of function. it's more readable and clear.

Make DrawCommand as Component

---

namui/namui-cli/src/cli.rs
namui/namui-cli/src/main.rs
namui/namui-cli/src/procedures/build.rs
namui/namui-cli/src/procedures/check.rs
namui/namui-cli/src/procedures/clippy.rs
namui/namui-cli/src/procedures/linux/wasm_linux_electron/build.rs
namui/namui-cli/src/procedures/linux/wasm_linux_electron/start.rs
namui/namui-cli/src/procedures/linux/wasm_unknown_web/build.rs
namui/namui-cli/src/procedures/linux/wasm_unknown_web/start.rs
namui/namui-cli/src/procedures/linux/wasm_unknown_web/test.rs
namui/namui-cli/src/procedures/linux/wasm_windows_electron/build.rs
namui/namui-cli/src/procedures/linux/wasm_windows_electron/start.rs
namui/namui-cli/src/procedures/linux/x86_64_pc_windows_msvc/build.rs
namui/namui-cli/src/procedures/start.rs
namui/namui-cli/src/procedures/test.rs
namui/namui-cli/src/services/drawer_watch_build_service.rs
namui/namui-cli/src/services/electron_build_service.rs
namui/namui-cli/src/services/electron_package_service.rs
namui/namui-cli/src/services/resource_collect_service.rs
namui/namui-cli/src/services/runtime_project/x86_64_pc_windows_msvc.rs
namui/namui-cli/src/services/rust_build_service.rs
namui/namui-cli/src/services/wasm_watch_build_service.rs
namui/namui-user-config/src/set_user_config.rs

Build with --release, no console on msvc

---

namui/namui-type/src/types/data_structure/serde_lru_cache.rs

https://rust-lang.github.io/rust-clippy/master/index.html#/blocks_in_conditions

Clippy on `namui-type`

---

x86_64-pc-windows.code-workspace.example

Wihtout '--tests', it doesn't run for cfg test.
Please update your workspace file.

Put tests on rust-analyzer

---

namui/namui-type/src/types/units/angle.rs

This supports Angle * Percent, etc.

Support multiply angle by ratio

---

namui/namui-hooks/src/compose/ctx/public/mod.rs
namui/namui-prebuilt/src/button.rs
namui/namui-prebuilt/src/scroll_view.rs
namui/namui-prebuilt/src/table/hooks.rs

Remove ref for compose

---

namui/namui-hooks/src/atom.rs
namui/namui-hooks/src/component/attach_event.rs
namui/namui-hooks/src/component/ctx/public_crate.rs
namui/namui-hooks/src/render_ctx.rs
namui/namui-hooks/src/set_state.rs
namui/namui-hooks/src/test/mod.rs
namui/namui-hooks/src/value.rs
namui/namui-hooks/src/world/mod.rs
namui/namui-hooks/src/world/public.rs

I tried to support RefCell for state, so I removed Send, Sync, and Debug. Actually they are not important derive attribute.

Remove unnecessary Send, Sync, Debug

---

namui/namui/src/namui/common/mod.rs
namui/namui/src/namui/common/resource_location.rs
namui/namui/src/namui/hooks/image.rs
namui/namui/src/namui/render/image.rs
namui/namui/src/namui/system/file/types/path_like.rs
namui/namui/src/namui/system/image/mod.rs
namui/namui/src/namui/system/skia/mod.rs
namui/sample/image-fit/Cargo.lock
namui/sample/image-fit/src/lib.rs
namui/sample/image-load-background/Cargo.lock
namui/sample/image-load-background/src/lib.rs

It's only applied to image. Audio may will be next time we need.
Closes #871 #870

Use `ResourceLocation` for image

---

namui/namui-cli/webCode/src/imports/envGl.ts

Turn on `glScissor`

---

namui/namui-cli/src/services/bundle/bundle_to_sqlite.rs
namui/namui-cli/src/services/resource_collect_service.rs
namui/namui/src/namui/system/file/bundle/mod.rs
namui/namui/src/namui/system/typeface/load_sans_typeface_of_all_languages.rs

Closes #878
Tested with my local and `image-load-background` sample.

Support sqlite bundle system in windows

---

namui/namui-cli/src/procedures/linux/x86_64_pc_windows_msvc/mod.rs
namui/namui-cli/src/procedures/linux/x86_64_pc_windows_msvc/start.rs
namui/namui-cli/src/procedures/start.rs

Namui-cli does not run built binary. It works like `build --watch`. Run the binary yourself

Impl msvc start procedure

---

.github/workflows/namui-linux-host-x86_64-pc-windows-msvc.yml

https://github.com/rust-cross/cargo-xwin/issues/114

use --locked for cargo-xwin install

---

namui/namui-cli/webCode/src/main-worker.ts

It's not imported
https://github.com/NamseEnt/namseent/blob/b518c8160302557d5c771cad70fd44468c9db64f/namui/namui-cli/webCode/src/main-worker.ts#L62

Import `sendMessageToMainThread` in main-worker

---

namui/namui-cli/build.rs
namui/namui/src/namui/mod.rs

closes https://github.com/NamseEnt/namseent/issues/876
Tested sample/bundle on wasm-wasi-web

Update wasi-sdk 23.0

---

namui/namui-prebuilt/src/vh_list_view.rs

`vh` is difficult to know what it means so I put the comment

Comment the name of vh list view

---

luda-adventure/Cargo.lock
luda-adventure/Cargo.toml
luda-adventure/src/app/game/save_load.rs
luda-adventure/src/app/game/test/character_should_escape_edge_of_wall.rs
luda-adventure/src/app/game/test/character_should_not_move_on_cross_axis_when_collide.rs
luda-adventure/src/ecs/app/save/mod.rs
luda-adventure/src/lib.rs
luda-editor/client/Cargo.toml
luda-editor/client/src/lib.rs
luda-editor/client/src/pages/sequence_edit_page/components/auto_complete_text_input/decomposed_string.rs
namui/namui-prebuilt/Cargo.lock
namui/namui-prebuilt/Cargo.toml
namui/namui-prebuilt/src/lib.rs
namui/namui-prebuilt/src/table/mod.rs
namui/sample/bundle/Cargo.toml
namui/sample/image-fit/Cargo.toml
namui/sample/image-load-background/Cargo.toml
namui/sample/media/Cargo.toml
namui/sample/mouse/Cargo.toml
namui/sample/multiline-text/Cargo.toml
namui/sample/rect/Cargo.toml
namui/sample/register-font/Cargo.toml
namui/sample/shader/Cargo.toml
namui/sample/tab-to-next-text-input/Cargo.toml
namui/sample/type_macro/Cargo.toml
namui/sample/typography-effect/Cargo.toml
quick/Cargo.lock
quick/Cargo.toml
quick/sample/tui/Cargo.toml
quick/src/lib.rs

We don't use wasm_bindgen anymore

Remove wasm_bindgen_test

---

namui/namui-hooks/src/component/component_trait.rs

If F: FnOnce, it's also F: Fn. Better!

impl Component for FnOnce instead Fn

---

namui/namui-hooks/src/component/ctx/mod.rs
namui/namui-hooks/src/component/ctx/public_crate.rs

Fix track_eq_tuple to use its own index

---

namui/namui/src/render/text_input/draw_texts_divided_by_selection.rs

text() was shadowed by text parameter

Qualify shadowed text rendering function

---

.github/workflows/namui-linux-host-wasm32-wasi-web.yml
luda-adventure/Cargo.lock
namui/namui-cli/build.rs
namui/namui-drawer/Cargo.toml
namui/namui-hooks/Cargo.toml
namui/namui-prebuilt/Cargo.toml
namui/namui-type/Cargo.toml
namui/namui/Cargo.toml
namui/sample/bundle/Cargo.toml
namui/sample/kv_store/Cargo.toml
namui/sample/mouse/Cargo.toml
namui/sample/rect/Cargo.toml
namui/sample/register-font/Cargo.toml
namui/sample/typography-effect/Cargo.toml
namui/skia/Cargo.toml
quick/Cargo.lock

and + Fix namui-cli's wrong wasi-wasi version check

Run wasm32-wasi-web ci/cd

---

namui/namui-cli/webCode/src/httpFetch/noStream.ts
namui/namui-cli/webCode/src/httpFetch/yesStream.ts
namui/namui-prebuilt/Cargo.lock
namui/namui/Cargo.lock
namui/namui/Cargo.toml
namui/namui/src/lib.rs
namui/namui/src/system/network/http/mod.rs
namui/namui/src/system/network/http/non_wasi.rs
namui/namui/src/system/network/http/wasi.rs
namui/sample/http/Cargo.lock
namui/sample/http/src/lib.rs

Http response stream

---

luda-editor/new-client/Cargo.lock
luda-editor/new-client/src/render_psd_sprite.rs
luda-editor/psd-sprite-render/Cargo.lock
luda-editor/psd-sprite-render/src/render_psd_sprite.rs
luda-editor/psd-sprite/src/lib.rs
luda-editor/psd-sprite/src/psd_sprite.rs

Remove SpriteParts

---

namui/namui-cli/webCode/src/insertJs.ts
namui/namui-cli/webCode/src/interWorkerProtocol.ts
namui/namui-cli/webCode/src/main.ts
namui/namui/src/system/wasi/insert_js.rs
namui/sample/insert-js/Cargo.lock
namui/sample/insert-js/Cargo.toml
namui/sample/insert-js/src/lib.rs
namui/sample/insert-js/src/login.js

Send data from rust to js

---

namui/namui/src/system/audio/opus.rs

Fix wrong byte index calculation

---

luda-editor/new-server/cdk/lib/AudioTranscodingStack.ts

Allow all origin for asset bucket cors

---

namui/namui-cli/webCode/src/httpFetch/yesStream.ts
namui/sample/http/Cargo.lock
namui/sample/http/server/.gitignore
namui/sample/http/server/index.mjs
namui/sample/http/server/package-lock.json
namui/sample/http/server/package.json
namui/sample/http/src/lib.rs

Use http/1 for http:// url

---

namui/namui-cli/webCode/src/eventSystem.ts

It was an independent issue with #833 
Closes #970

Fix wrong buffer index on emitting wheel event

---

luda-editor/new-client/src/asset_manage_page.rs
luda-editor/new-client/src/episode_editor/mod.rs
luda-editor/new-client/src/episode_editor/properties_panel.rs
luda-editor/new-client/src/episode_editor/scene_list.rs
luda-editor/new-client/src/episode_editor/scene_preview.rs
luda-editor/new-client/src/episode_editor/scene_sprite_editor/mod.rs
luda-editor/new-client/src/episode_editor/scene_sprite_editor/position_tool.rs
luda-editor/new-client/src/episode_editor/scene_sprite_editor/scene_sprite_list.rs
luda-editor/new-client/src/episode_editor/scene_sprite_editor/size_tool.rs
luda-editor/new-client/src/episode_editor/scene_sprite_editor/sprite_select_tool.rs
luda-editor/new-client/src/home.rs
luda-editor/new-client/src/lib.rs
luda-editor/new-client/src/new_episode_page.rs
luda-editor/new-client/src/psd_sprite_util/mod.rs
luda-editor/new-client/src/psd_sprite_util/psd_sprite_storage.rs
luda-editor/new-client/src/psd_sprite_util/render_psd_sprite.rs
luda-editor/new-client/src/router.rs
luda-editor/new-server/rpc/src/types/mod.rs
luda-editor/psd-sprite/src/psd_sprite.rs

Impl scene sprite editor

---

luda-editor/new-client/src/asset_manage_page.rs

Upload audio asset

---

luda-editor/new-client/src/asset_manage_page.rs
luda-editor/new-client/src/episode_editor/mod.rs
luda-editor/new-client/src/new_episode_page.rs
luda-editor/new-client/src/new_project_page.rs
luda-editor/new-client/src/new_team_page.rs

Add go back buttons

---

luda-editor/new-client/Cargo.lock
namui/namui-prebuilt/Cargo.lock
namui/namui/Cargo.lock
namui/namui/Cargo.toml

Use opusic-sys 0.5.2

---

luda-editor/new-server/database/schema/0/src/team.rs
luda-editor/new-server/rpc/src/lib.rs
luda-editor/new-server/rpc/src/types/mod.rs
luda-editor/new-server/server/src/api/asset/update_asset_tags_for_asset.rs
luda-editor/new-server/server/src/api/auth/session_token_auth.rs
luda-editor/new-server/server/src/api/episode/create_new_episode.rs
luda-editor/new-server/server/src/api/episode/get_episodes.rs
luda-editor/new-server/server/src/api/episode_editor/exit_episode_editor.rs
luda-editor/new-server/server/src/api/episode_editor/get_speaker_names.rs
luda-editor/new-server/server/src/api/episode_editor/join_episode_editor.rs
luda-editor/new-server/server/src/api/episode_editor/load_speaker_slots.rs
luda-editor/new-server/server/src/api/episode_editor/save_speaker_slots.rs
luda-editor/new-server/server/src/api/episode_editor/try_edit_episode.rs
luda-editor/new-server/server/src/api/project/delete_speaker.rs
luda-editor/new-server/server/src/api/project/list_speakers.rs
luda-editor/new-server/server/src/api/project/mod.rs
luda-editor/new-server/server/src/api/project/put_speaker.rs
luda-editor/new-server/server/src/api/team/get_my_teams.rs

Speaker CRUD

---

.github/workflows/namui-linux-host-x86_64-unknown-linux-gnu.yml

Install libfontconfig-dev package

---

namui/namui-type/src/types/units/vector_types/macros.rs

Add AsRef for vector types

---

tower-defense/src/game_state/mod.rs
tower-defense/src/game_state/monster_spawn.rs
tower-defense/src/route/move_on_route.rs

Spawn monster

---

tower-defense/src/game_state/item.rs
tower-defense/src/game_state/mod.rs
tower-defense/src/inventory.rs
tower-defense/src/lib.rs
tower-defense/src/shop.rs
tower-defense/src/upgrade.rs

- shop
- inventory
- using item
- generating item list randomly

Impl item related UIs

---

tower-defense/src/game_state/mod.rs
tower-defense/src/game_state/monster.rs
tower-defense/src/game_state/monster/mod.rs
tower-defense/src/game_state/monster/skill.rs
tower-defense/src/game_state/tick.rs
tower-defense/src/game_state/tower/mod.rs
tower-defense/src/game_state/tower/skill.rs

Monster and tower's status effects are not calculated yet. will do on next pr.

Tower Skill

---

tower-defense/src/game_state/camera.rs
tower-defense/src/game_state/mod.rs
tower-defense/src/game_state/render.rs
tower-defense/src/lib.rs

Todo
- clamp camera.left_top
- can not tested because render performance issue on zoom out and move to right end

Impl camera move and zoom

---

tower-defense/src/game_state/item.rs
tower-defense/src/game_state/mod.rs
tower-defense/src/game_state/quest.rs
tower-defense/src/game_state/quest/mod.rs
tower-defense/src/game_state/quest/requirement.rs
tower-defense/src/game_state/quest/reward.rs
tower-defense/src/game_state/tower/mod.rs
tower-defense/src/lib.rs
tower-defense/src/quest_board.rs
tower-defense/src/quests.rs
tower-defense/src/upgrade.rs

- quest
- quest generating
- quest board
- current quests

Add quest features

---

tower-defense/src/game_state/can_place_tower.rs

Test made by gpt 4o

---

tower-defense/src/game_state/projectile.rs
tower-defense/src/game_state/render.rs

Render just green ball for now

Render projectiles

---

tower-defense/src/game_state/can_place_tower.rs
tower-defense/src/route/mod.rs

closes #1048
Please test 1048 case, @bigfoodK

Fix wrong Path Disrupt calculation

---

tower-defense/src/lib.rs
tower-defense/src/settings.rs

Add settings modal

---

tower-defense/src/inventory.rs
tower-defense/src/quests.rs

I used attach_event() in ghost_compose, that was problem

Fix buttons in quests, inventory

---

.github/workflows/deploy-luda-editor.yml_disabled
.github/workflows/publish-extension.yml

fixes https://github.com/NamseEnt/namseent/actions/runs/14338110238/job/40190329798

Upgrade sccache action from 0.3 to 0.8

---

namui/namui-cli/webCode/src/main.ts
namui/namui-drawer/src/draw/mod.rs
namui/namui-drawer/src/lib.rs
namui/namui-hooks/src/compose/ctx/compose_command.rs
namui/namui-hooks/src/compose/ctx/mod.rs
namui/namui-hooks/src/compose/ctx/public/event.rs
namui/namui-hooks/src/compose/ctx/public/stack.rs
namui/namui/src/system/screen/wasm.rs
namui/namui/src/system/skia/mod.rs
namui/skia/src/bounding_box/rendering_tree.rs
namui/skia/src/render/rendering_tree/mod.rs
namui/skia/src/render/rendering_tree/special/mod.rs
namui/skia/src/render/rendering_tree/special/mouse_cursor.rs
namui/skia/src/xy_in/mod.rs
namui/skia/src/xy_in/rendering_tree.rs

Custom mouse cursor, Default cursor only

---

namui/namui-type/src/types/units/matrix.rs
namui/namui-type/src/types/units/rect.rs
namui/skia/src/bounding_box/rendering_tree.rs
namui/skia/src/render/rendering_tree/special/absolute.rs
namui/skia/src/render/rendering_tree/special/translate.rs

Matrix calculation was wrong so rotated object's bounding box was wrong.

Fix rotated bounding box problem

---

tower-defense/src/asset_loader/background_asset_loader.rs
tower-defense/src/asset_loader/tower_asset_loader.rs
tower-defense/src/card.rs
tower-defense/src/game_state/can_place_tower.rs
tower-defense/src/game_state/field_area_effect/mod.rs
tower-defense/src/game_state/flow.rs
tower-defense/src/game_state/item/usage.rs
tower-defense/src/game_state/mod.rs
tower-defense/src/game_state/monster/mod.rs
tower-defense/src/game_state/monster/skill.rs
tower-defense/src/game_state/quest/mod.rs
tower-defense/src/game_state/quest/tracking.rs
tower-defense/src/game_state/tick.rs
tower-defense/src/game_state/tower/mod.rs
tower-defense/src/game_state/tower/render.rs
tower-defense/src/game_state/upgrade/generation.rs
tower-defense/src/lib.rs
tower-defense/src/route/mod.rs
tower-defense/src/route/route_find.rs
tower-defense/src/shop.rs
tower-defense/src/top_bar/mod.rs
tower-defense/src/tower_selecting_hand/get_highest_tower.rs
tower-defense/src/upgrade_board.rs

I forgot to turn on clippy on IDE after formatting my pc

Clippy tower defense

---

namui/skia/src/render/event/raw.rs

It's useful when move it to closure

Clone raw event

---

tower-defense/src/asset_loader/icon_asset_loader.rs
tower-defense/src/game_state/field_particle/emitter/damage_text.rs
tower-defense/src/game_state/field_particle/emitter/mod.rs
tower-defense/src/game_state/field_particle/mod.rs
tower-defense/src/game_state/field_particle/particle/damage_text.rs
tower-defense/src/game_state/field_particle/particle/mod.rs
tower-defense/src/game_state/tick.rs

Emit damage indicator on enemy hits

---

tower-defense/src/card.rs
tower-defense/src/game_state/cursor_preview/mod.rs
tower-defense/src/game_state/cursor_preview/tower.rs
tower-defense/src/game_state/flow.rs
tower-defense/src/game_state/hand/hand_slot.rs
tower-defense/src/game_state/hand/mod.rs
tower-defense/src/game_state/hand/render_card.rs
tower-defense/src/game_state/hand/render_tower.rs
tower-defense/src/game_state/hand/shared.rs
tower-defense/src/game_state/hand/xy_with_spring.rs
tower-defense/src/game_state/mod.rs
tower-defense/src/game_state/tick.rs
tower-defense/src/lib.rs
tower-defense/src/tower_placing_hand/mod.rs
tower-defense/src/tower_selecting_hand/mod.rs

Sort cards

---

tower-defense/Cargo.toml
tower-defense/src/asset_loader/background_asset_loader.rs
tower-defense/src/game_state/field_particle/emitter/mod.rs
tower-defense/src/game_state/quest/mod.rs
tower-defense/src/game_state/quest/reward.rs
tower-defense/src/inventory.rs
tower-defense/src/l10n/api.rs
tower-defense/src/l10n/locale.rs
tower-defense/src/top_bar/level_up_details.rs
tower-defense/src/tower_selecting_hand/get_highest_tower/tests/four_of_a_kind.rs
tower-defense/src/tower_selecting_hand/get_highest_tower/tests/full_house.rs
tower-defense/src/tower_selecting_hand/get_highest_tower/tests/mod.rs
tower-defense/src/tower_selecting_hand/get_highest_tower/tests/one_pair.rs
tower-defense/src/tower_selecting_hand/get_highest_tower/tests/straight_flush.rs
tower-defense/src/tower_selecting_hand/get_highest_tower/tests/three_of_a_kind.rs
tower-defense/src/tower_selecting_hand/get_highest_tower/tests/two_pair.rs
tower-defense/src/tower_selecting_hand/get_highest_tower/tower_status_effect_injector.rs
tower-defense/src/tower_selecting_hand/tower_preview/mod.rs
tower-defense/src/upgrade_board.rs

Fix inventory wrong scroll view usage

---

tower-defense/src/game_state/hand/mod.rs
tower-defense/src/game_state/mod.rs
tower-defense/src/game_state/modal.rs
tower-defense/src/game_state/start_confirm_modal.rs
tower-defense/src/l10n/api.rs
tower-defense/src/l10n/ui.rs
tower-defense/src/lib.rs
tower-defense/src/settings.rs
tower-defense/src/tower_placing_hand/mod.rs
tower-defense/src/upgrade_board/components.rs

Show confirm modal on force start if hand is not empty
