NamseEnt/namseent

- luda/editor/client/src/timeline/clip/SubtitleClipComponent.ts
- namui/src/ColorUtil.ts
It uses functions similar to, but not equal to, crc32 hash functions.
`ColorUtil.getRandomColorFromString(seed: string, withAlpha?: boolean)`
Color range is rgba(0-255, 0-255, 0-255, 0-1)
If `withAlpha` option activated, color's alpha also will be random. If not, alpha will be `1`.
It closes #19
> Generate random color from string

- luda/editor/client/src/cameraAngleEditor/imageBrowser/SyncBrowserItems.ts
- namui/src/image/ImageLoadManager.ts
'-' is the separator of image name.
But some of image, it use '-' to describe emotion.
Not only '-' to describe emotion
So I make it possible to use '-' in emotion in file.
Maybe we should change the separator from '-' to other thing later.
> Support '-' in image name

- luda-editor/luda-editor-client/src/editor/clip_editor/camera_clip_editor/image_browser/back_button.rs
- luda-editor/luda-editor-client/src/editor/clip_editor/camera_clip_editor/image_browser/browser_item.rs
- luda-editor/luda-editor-client/src/editor/clip_editor/camera_clip_editor/image_browser/mod.rs
- luda-editor/luda-editor-client/src/editor/clip_editor/mod.rs
- luda-editor/luda-editor-client/src/editor/job/mod.rs
- luda-editor/luda-editor-client/src/editor/mod.rs
- luda-editor/luda-editor-client/src/editor/timeline/timeline_body/track_body/camera_track_body/mod.rs
- luda-editor/luda-editor-client/src/editor/types.rs
- luda-editor/luda-editor-server/src/main.rs
- namui/src/namui/draw/image.rs
- namui/src/namui/font/load_sans_typeface_of_all_languages.rs
- namui/src/namui/manager/web/image_manager.rs
- namui/src/namui/namui_common.rs
- namui/src/namui/namui_web/fetch.rs
- namui/src/namui/namui_web/mod.rs
- namui/src/namui/render/image.rs
- namui/src/namui/render/path.rs
- namui/src/namui/render/rect.rs
- namui/src/namui/render/rendering_tree.rs
- namui/src/namui/skia/web/typeface.rs
- nrpc/src/def_rpc.rs
- nrpc/src/response_waiter.rs
- rustfmt.toml
> English follows
rust-analyzer가 vscode에서 타입 힌트를 화면에 보여주는데, 만약 타입이 길 경우 코드의 너비가 화면보다 더 커서 코드의 일부가 보이지 않을 때가 있습니다.
이 문제를 해결하기 위해 저는 rustfmt의 설정으로 한 줄의 길이를 제한하려고 했습니다만, 그렇게까지 효과적이지 않았습니다.
특히, 저는 chaining의 너비를 줄이려고 했습니다. 하지만 제가 줄이고 싶었던 chaining은 builder-pattern같은 method chaining(a().b().c() 같은)인데, 그것 말고 a.b.c 같은 property chaining도 너비가 줄어들더라고요. 그건 원치 않았는데, 그것만 따로 설정하는건 없었습니다.
그래서 마땅한 아이디어가 떠오르기 전까지는 rustfmt를 default 설정으로 바꾸려고 합니다. 만약 괜찮은 rustfmt 설정값을 누구든 찾는다면 공유하고 토론해봅시다.
rust-analyzer shows type hints in vscode on the screen, but if the type is long, the width of the code is larger than the screen, so part of the code is sometimes not visible.
To solve this problem, I tried limiting the length of a single line with a setting in rustfmt, but it didn't work that far.
Specifically, I tried to …
> Rollback rustfmt to default

- namseent.code-workspace
> English follows
우리는 rust cargo workspace를 사용하지 않기로 결정했습니다. 왜냐하면 rust에서 wasm를 사용할 때, wasm에서 빌드하지 못하는 dependency를 cargo workspace에서 체크하는 문제가 있기 때문입니다.
cargo workspace를 없애면 vscode로 root 디렉토리를 켜서 작업할 수 없습니다. cargo workspace 없이는 root 디렉토리에선 rust-analyzer가 동작하지 않기 때문입니다.
이러한 불편함을 개선하기 위해 vscode multi-root workspace를 도입합니다. 엄청나게 편하진 않을지라도, vscode를 여러개 켜야하는 것보단 더 나을 것이라 예상됩니다.
We decided not to use the rust cargo workspace. This is because when using wasm in rust, there is a problem in cargo workspace checking for dependencies that wasm cannot build.
Because of removing the cargo workspace, you won't be able to work in rust, when you open the root directory with vscode. This is because rust-analyzer will not run in the root directory without cargo workspace.
To alleviate this inconvenience, …
> Support vscode multi-root workspace

- luda-editor/luda-editor-client/Cargo.toml
I found that default profile in wasm-unknown-unknown is toooooo slow to draw about 20~30 rectangle. I think putting opt-level 2 is not a bad idea because we use incremental building so building is not slow as much as I expected.
> Set luda-editor-client dev profile opt-level = 2

- luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/scroll.rs
- luda-editor/luda-editor-client/src/app/editor/events.rs
- luda-editor/luda-editor-client/src/app/editor/job/move_camera_clip.rs
- luda-editor/luda-editor-client/src/app/editor/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/subtitle_track_body/subtitle_clip_body.rs
- luda-editor/luda-editor-client/src/app/editor/types/mod.rs
- luda-editor/luda-editor-client/src/app/types/mod.rs
- luda-editor/luda-editor-client/src/app/types/time.rs
- luda-editor/luda-editor-client/src/app/types/time_per_pixel.rs
- namui/src/namui/common/mod.rs
- namui/src/namui/manager/web/keyboard_manager/mod.rs
- namui/src/namui/mod.rs
- namui/src/namui/namui_web/mod.rs
- namui/src/namui/render/mod.rs
- namui/src/namui/render/rect.rs
- namui/src/namui/render/rendering_tree.rs
- namui/src/namui/render/text_input/render/get_selection_on_mouse_down.rs
- namui/src/namui/render/with_id.rs
- namui/src/namui/skia/base/paint_builder.rs
- namui/src/namui/skia/base/path_builder.rs
I ported timeline body zooming and moving.
- Move and zoom timeline with wheel : 792b793d75d7459f51ad9ed1d5a7b3b85c43fb4e
- Retype time as f32 : 51bcbaee96081b33e69cdb0b4cf2107e4ea149d0
- Remove log : bd9531863c53c03ae40184ed088dca90139e8c9b 
- Prevent key down default for alt key only : 69e5c18279449dab38304e8d37524802c523e787
- This is for alt-tab enabling.
- Get rendering tree xy using id : d49bef1946a785385ef235bacf4faaa140dddcb5
- Prevent key down default to keep focus on alt key : 55a62464cf197ae06a072d02c55532bea826471a
- Expose Code from namui : eae628830f705e418574b3f56fa848cd4ba5beaa
There are many namui changes, so please merge using **rebase**.
> Zome and move timeline

- luda-editor/luda-editor-client/Cargo.toml
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/subtitle_track_body/subtitle_clip_body.rs
- luda-editor/luda-editor-client/src/app/types/pixel_size.rs
- luda-editor/luda-editor-client/src/app/types/time.rs
I overloaded Time and PixelSize's arithmetic operator's using [impl_op macro](https://docs.rs/auto_ops/latest/auto_ops/).
> Overload Time, PixelSize ops in macro

- namui/src/namui/manager/web/keyboard_manager/mod.rs
When namui_web handles keyboard input, it changes keyboard event to [code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values).
But I didn't put every code in our system.
So this PR check whether the code has been added in our system or not and resolve below error
> Filter unknown keyboard code

- luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/back_button.rs
- luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/browser_item.rs
- luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/scroll.rs
- luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/wysiwyg_editor/cropper.rs
- luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/wysiwyg_editor/mod.rs
- luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/wysiwyg_editor/resizer.rs
- luda-editor/luda-editor-client/src/app/editor/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/camera_track_body/camera_clip_body.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/subtitle_track_body/subtitle_clip_body.rs
- luda-editor/luda-editor-client/src/app/sequence_list/load_button.rs
- luda-editor/luda-editor-client/src/app/sequence_list/mod.rs
- luda-editor/luda-editor-client/src/app/sequence_list/open_button.rs
- namui/Cargo.toml
- namui/src/namui/event/mod.rs
- namui/src/namui/font/load_sans_typeface_of_all_languages.rs
- namui/src/namui/manager/web/mouse_manager.rs
- namui/src/namui/manager/web/screen_manager.rs
- namui/src/namui/manager/web/wheel_manager.rs
- namui/src/namui/mod.rs
- namui/src/namui/render/text_input/render/mod.rs
Previously, we have to call `namui::event::send(Box::new(Event))` to send event to namui. It's toooooo anoying to put `Box::new` everytime.
I found that we don't have to put `Box::new` everytime, just pass event as `impl Any + Send + Sync` and just box it inside of send function.
> Box namui::event internally

- namui/src/namui/common/mod.rs
- namui/src/namui/common/set_timeout.rs
- namui/src/namui/mod.rs
I put set_timeout in namui.
- namui store callback in binary-min-heap (or priority queue), sorting by time user requested.
- namui pop callback from heap on event loop.
- this means, current set_timeout's timing is not accurate. I think it's not necessary to support accurate set-timeout for now.
> Support set_timeout

- namui/src/namui/skia/web/path.rs
Previous
```
x 0 0
y 0 0
0 0 1
```
It's wrong. It's not X,Y Scale Matrix. it just make (1,1) vector to (x + y, 0).
I fixed like below.
```
x 0 0
0 y 0
0 0 1
```
> Fix wrong scaling linear transformation matrix

- namui/src/namui/common/mod.rs
- namui/src/namui/common/request_animation_frame.rs
- namui/src/namui/common/set_timeout.rs
- namui/src/namui/mod.rs
I made `request_animation_frame` api for user, not inside of namui.
- With current implementation, user cannot draw what they want to draw right that frame using `request_animation_frame`.
- Let's assume that `SequencePlayer` uses `request_animation_frame` to render on every frame.
- Without `request_animation_frame`, it's not possible to render on right frame because namui only `render` after update by event, just `draw` in namui's internal AnimationFrame.
- `SequencePlayer` want to render when it call `request_animation_frame`, so it call `namui::event::send` in `request_animation_frame` like below
```rust
impl SequencePlayer {
fn update() {
if event == SequencePlayerEvent::AnimationFrame {
request_animation_frame(|| {
namui::event::send(SequencePlayerEvent::AnimationFrame)
}
}
}
}
``` …
> Request animation frame from namui user

- namui/src/namui/common/mod.rs
- namui/src/namui/event/mod.rs
- namui/src/namui/mod.rs
- namui/src/namui/namui_mock/mod.rs
- namui/src/namui/namui_web/mod.rs
Error occurred when using `namui::event::send()` while making `namui::Entity` for the first time.
This was because the event channel had not been created yet.
This pr makes event channel to be created in `namui::init` step.
> Init event receiver on namui::init

- luda-editor/luda-editor-client/src/app/editor/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/mod.rs
It's simple pull request.
I found that Editor handle some event about only for timeline. it even change timeline like `self.timeline.xxx = yyy`.
Hmm. I think it should be in timeline code. so I moved it from editor to timeline.
> Move timeline event handling from editor

- luda-editor/luda-editor-client/src/app/editor/mod.rs
- luda-editor/luda-editor-client/src/app/editor/top_bar/events.rs
- luda-editor/luda-editor-client/src/app/editor/top_bar/go_back_button.rs
- luda-editor/luda-editor-client/src/app/editor/top_bar/mod.rs
- luda-editor/luda-editor-client/src/app/events.rs
It's just a button to go back.
If you press the button inside the editor page, you will go to the sequence list page.
> Add go-back button in editor page

- .github/workflows/check.yml
- luda-editor/luda-editor-client/.gitignore
I remove luda-editor-client from cargo check action because that packages will be checked by test-luda-editor-client action.
> Remove luda-editor-client cargo checking action

- namui/src/namui/render/rendering_tree.rs
I couldn't get the mouse event for the rendering tree which used `absolute()`. So I digged it and found it's because of wrong local xy calculation for `absolute` on mouse event handling.
> Fix wrong local xy calculation for aboluste

- namui/src/namui/font/load_sans_typeface_of_all_languages.rs
- namui/src/namui/namui_web/fetch.rs
I thought our ImageManager can recover from error of fetching image. But it doesn't, it become panic.
I found that fetch logic used unwrap, so it was not recovered even it's return type was Result.
I changed unwrap-ing code into question mark operator, which return Err instead of panic.
> Recover from fetch fail error

- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/camera_track_body/camera_clip_body.rs
- luda-editor/luda-editor-client/src/app/types/camera_angle.rs
In the timeline, it was very difficult to distinguish the camera clips. Because all the clips were the same color and the same shape.
I show camera clip preview in camera clip body, like other video editing tools.
https://docs.google.com/document/d/1bs7z9n0Oy0qpS-00k946Yz69BYClqtIpL5pBrh10HLA/edit#
> Show camera clip preview on timeline

- luda-editor/luda-editor-client/src/app/editor/events.rs
- luda-editor/luda-editor-client/src/app/editor/job/add_camera_clip.rs
- luda-editor/luda-editor-client/src/app/editor/job/mod.rs
- luda-editor/luda-editor-client/src/app/editor/job/move_camera_clip.rs
- luda-editor/luda-editor-client/src/app/editor/job/resize_camera_clip.rs
- luda-editor/luda-editor-client/src/app/editor/job/test_utils.rs
- luda-editor/luda-editor-client/src/app/editor/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/camera_track_body/camera_clip_body/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/camera_track_body/camera_clip_body/sash.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/camera_track_body/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/mod.rs
- luda-editor/luda-editor-client/src/app/types/camera_track.rs
Did you know that there are no functionality to resize the camera clip until now!?
but, from now on, you can resize the camera clip using sash~
(Actually we already did it on typescript version~)
No left sash. Because if we resize using left sash, it should affect to timeline.start_at, but it seems not easy to do that. By priority, I think it's not necessary to support left sash right now. So I just implemented about right sash.
https://docs.google.com/document/d/1iD2e1NfCoR7sWDg4Z5s-j9247dn8usq2hBA5cn_A7CM/edit#
> Resize camera clip using sash

- namui/src/namui/render/text.rs
Previously, If I tried to draw '...' using namui::text with background, the background's height was same with height of `...`.
Like below!
So I edit to keep minimum height using font size.
Like below!
> Keep minimum height for text background

- luda-editor/luda-editor-client/src/app/editor/mod.rs
If I click one clip, and press Shift+End
OH NYO~ Why it select the previous clip!?
> Because I made a code like that :(
> Exclude crossing clip during select clips at once

- luda-editor/luda-editor-client/src/app/editor/clip_select.rs
- luda-editor/luda-editor-client/src/app/editor/mod.rs
I found that when I click new image in image browser(in camera clip editor), it reset the scroll!
The reason was.... it updated selected clip ids.
So I fix up how to manage selected clip ids in editor. 
little design docs : https://docs.google.com/document/d/1yX9ix_xjwPn-spT6Kd-yDFLbomwpNkyr_QfXxBkqYWs/edit#
> Keep image browser scroll on select image

- namui/src/namui/render/rendering_tree.rs
As a below note, event trigger's order is RLN but namui didn't call sub tree's mouse event.
```
/// NOTE
/// Order of tree traversal is important.
/// - draw = pre-order dfs (NLR)
/// - events = Reverse post-order (RLN)
```
child rendering tree's attach_event doesn't call if parent attach event too
```
let a = render![].attach_event(...); // a's event trigger doesn't called
let b = a.attach_event(..); // b's trigger called
```
Wheel event is ok, they use visit_rln function that support rln well. It's only problem about mouse event.
> Call sub tree's event handler before node

- luda-editor/luda-editor-client/Cargo.toml
- luda-editor/luda-editor-client/src/app/editor/clip_select.rs
- luda-editor/luda-editor-client/src/app/editor/events.rs
- luda-editor/luda-editor-client/src/app/editor/mod.rs
- luda-editor/luda-editor-client/src/app/editor/sequence_player/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/camera_track_body/camera_clip_body/mod.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/track_body/subtitle_track_body/subtitle_clip_body.rs
- luda-editor/luda-editor-client/src/app/sequence_list/mod.rs
- namui/src/namui/common/mod.rs
- namui/src/namui/manager/web/mouse_manager.rs
- namui/src/namui/mod.rs
- namui/src/namui/render/rendering_tree.rs
There are 4 commits.
- Support id in event (80f7cc6e7f20fd47e83373619c9f2c5e6a79593d)
- it's to find out if an empty track body is clicked.
- Mock SequncePlayer (47c8ee5c44d38adc7af803797444328218a178b0)
- To make a mocked editor in test code.
- Handle shift+click with time (d753e17802c01f74d919a4bbf2f611af0607e2d2)
- Previously we calculated shift+click using clip ids but it wasn't good idea because there are swallowed clips (example : 1.start--2.start---2.end--1.start).
- I put test codes together.
- Support click track empty body (14a07a1906102978c79c03e62e7854d1db8d2072)
- Design doc for this commit : https://docs.google.com/document/d/1TwxQNqeW7EIuoxfoUpfA8fPmDXaXAvONKKIHBJQrX6A/edit#
> Support click track empty body 

- luda-editor/luda-editor-client/src/app/editor/mod.rs
Previously all ctrl+ or shift+ command worked with left key.
I put the support for right shift and right ctrl.
it's very important to edit on luda editor because left shift key is very far from 'End' key, which I usually use it(shift+end).
> Support right shift and ctrl command on luda editor

- luda-editor/luda-editor-client/Cargo.toml
- luda-editor/luda-editor-client/src/app/editor/clip_select.rs
- luda-editor/luda-editor-client/src/app/types/meta.rs
- luda-editor/luda-editor-client/src/app/types/subtitle_play_duration_measure.rs
- luda-editor/resources/meta.json
https://github.com/NamseEnt/namseent/issues/140#issue-1167625617
> When the subtitle contains `...` or `,`, it should make subtitle duration longer. It should has different duration between `...` and `,`.
> 
> So I got a needs to calculate subtitle duration in different way when it comes to with specific text token.
Add `subtitle_specific_text_token_play_duration_map` to `meta.json`.
You can add token like this
```json
{
"subtitle_language_minimum_play_duration_map": {..},
"subtitle_language_play_duration_per_character_map": {..},
"subtitle_specific_text_token_play_duration_map": {
"...": {
"milliseconds": 200.0
}
},
"subtitle_character_color_map": {..}
}
```
Now `subtitle_play_duration_measure` calculates duration like following
1. Iter tokens in …
> Calculate subtitle duration with specific text token

- namui-cli/Cargo.toml
- namui-cli/electron/.gitignore
- namui-cli/electron/package.json
- namui-cli/electron/src/main.js
- namui-cli/scripts/install.sh
- namui-cli/scripts/uninstall.sh
- namui-cli/src/main.rs
- namui-cli/src/procedures/dev_wasm_electron.rs
- namui-cli/src/procedures/mod.rs
- namui-cli/src/services/electron_dev_service.rs
- namui-cli/src/services/mod.rs
- namui-cli/src/services/rust_build_service.rs
- namui-cli/src/services/wasm_bundle_web_server.rs
- namui-cli/src/util/get_cli_root_path.rs
- namui-cli/src/util/mod.rs
- Update install/uninstall script for setup electron
- Add electron sub project
- Add dev_wasm_electron procedure
- Run wasm build with `dev` and `wasm-electron` flag
- Run wasm bundle dev server
- Run electron that connects to wasm bundle dev server
Running the gpu app on wsl is a nuisance. So we runs `electron.exe` from windows while in wsl.
But if `electron.exe` and dlls are on wsl path, there is a problem that does not work properly.
So in wsl, install script will install electron to windows and `ElectronDevService` uses electron in windows.
> Add dev_wasm_electron procedure

- namui-cli/scripts/install.sh
- namui-cli/scripts/uninstall.sh
I found cargo bin doesn't always exist at `$Home/.cargo/bin`. For example, on rust alpine docker, cargo was in `/usr/local/cargo/bin/cargo`.
> Fix way to get cargo bin path

- namui-cli/scripts/install.sh
`uname` uses kernel's name. In docker, it's same so if I run docker image in wsl, container also say it's wsl. So I fixed the way to get it's wsl or not by finding explorer.exe.
> Detect wsl by finding explorer.exe

- namui/src/namui/draw/mod.rs
- namui/src/namui/draw/text.rs
- namui/src/namui/render/matrix.rs
- namui/src/namui/render/rendering_tree.rs
- namui/src/namui/skia/base/path_builder.rs
- namui/src/namui/skia/types.rs
- namui/src/namui/skia/web/canvas_kit/path.rs
- namui/src/namui/skia/web/font.rs
- namui/src/namui/skia/web/path.rs
- Implement getting bounding box of rendering tree, rendering data, draw command!
- Use bounding box to check mouse is in text or not.
> Get bounding box of rendering tree

- namui-prebuilt/src/scroll_view.rs
If multiple ScrollViews exist, single `Scrolled` event will scroll every views.
I put id in view and use it on event.
> Identity event source

- namui/src/namui/common/mod.rs
- namui/src/namui/draw/text.rs
- namui/src/namui/font/load_sans_typeface_of_all_languages.rs
- namui/src/namui/manager/common/font_manager.rs
- namui/src/namui/mod.rs
- namui/src/namui/namui_mock/mod.rs
- namui/src/namui/namui_web/mod.rs
- namui/src/namui/skia/web/canvas.rs
- namui/src/namui/skia/web/canvas_kit/text_blob_factory.rs
- namui/src/namui/skia/web/font.rs
- namui/src/namui/skia/web/text_blob.rs
- namui/src/namui/skia/web/typeface.rs
Yes, namui support emoji using [NotoColorEmoji](https://github.com/googlefonts/noto-emoji)!
1. namui try to draw text with font that user set when they call namui::text.
2. If namui fail to draw text with font, it use 'fallback font'.
3. Ah, Yas, I make namui load noto emoji as fallback font.
> Fallback emoji font

- .github/workflows/namui-test-host-linux.yml
- docker-images/namui-test-host/linux.Dockerfile
To use namui-cli in namui-cfg in test, I put namui-cli inside of namui-test-host docker image
> Install namui-cli in namui-test-host docker image

- namseent.code-workspace
Vscode sometimes open root directory when I open file.
For example, when i open namui/src/lib.rs, it open namseent/namui/src/lib.rs.
I think it's kind of vscode bug.
So I suggest to open root if user really need to edit something that can access from root.
> Remove root from code-workspace

- .github/actions/namui-test/action.yml
- luda-editor/luda-editor-client/Cargo.lock
I found that sometime we don't push updated Cargo.lock when we update Cargo.toml. I found how CI can catch it before merge pull requests.
context: https://github.com/rust-lang/rust-analyzer/issues/12219
> Check Cargo.lock in CI

- namui/src/namui/skia/types.rs
I found bug in code. I have no idea why it worked before.
original PR : https://github.com/NamseEnt/namseent/pull/165
> Fix wrong ltrb intersect operation

- namui/src/namui/manager/common/typeface_manager.rs
I got a error message that dropped typeface reused in canvaskit. To avoid that problem, I wrap typeface with arc. I think I reverted it in previous PR. --> https://github.com/NamseEnt/namseent/commit/d02165d95be9d566cab84551af3c04638ffa57f0#diff-9a9aca6cc9da3533e1a18cef81db49c3306ac59f6808885dd33f05a2c8aae4f8R6
related PR: https://github.com/NamseEnt/namseent/pull/184
> Wrap typeface with arc

- namui/sample/text-input/src/lib.rs
- namui/src/namui/manager/web/text_input_manager.rs
- namui/src/namui/mod.rs
- namui/src/namui/render/text_input/mod.rs
I removed focus boolean from text_input because it would not sync if user didn't update it.
Only single text_input can be focused, so I decide hiding focus information from text_input, and put it into manager.
During that editing, I passed text_input id in blur event so user can check that text input is done or not.
> Hide text input focus information

- namui-cli/src/procedures/linux/wasm_unknown_web/test.rs
I found that when `namui test` fail, it doesn't chmod outputs, like `target`. So after failure, when I run `cargo check`, it makes permission error like this.
To solve this problem, I saved exit code and run chmod then exit with previous exit code.
> Chmod test outputs before exit

- luda-editor/luda-editor-client/src/app/editor/clip_editor/camera_clip_editor/image_browser/scroll.rs
- luda-editor/luda-editor-client/src/app/editor/timeline/timeline_body/mod.rs
- namui-prebuilt/src/scroll_view.rs
- namui/src/namui/common/mod.rs
- namui/src/namui/mod.rs
- namui/src/namui/render/rendering_tree/mod.rs
- namui/src/namui/render/special/attach_event.rs
Previously we put rendering-tree-xy-getting-method using renderingTree's reference. So in wheel event, I put the way to get local xy easily using namui context and target.
> Get local xy in wheel event without id

- namui/src/namui/manager/web/keyboard_manager.rs
I found that Alt+ArrowLeft activate `go back` button. I prevent it with code clean (https://github.com/NamseEnt/namseent/issues/185)
> Prevent arrow & space key for scroll & history move

- namui/src/namui/manager/web/keyboard_manager.rs
I found that document.blur or document.visibilitychange event weren't called when I switch to other window which cover whole web page.
I mean, if I switch to small, pop-up-styled, window like Kakao Talk, it doesn't call blur or visibilitychange.
I found solution from stackoverflow, so window.blur will called if user switch window even into popup window.
reference: https://stereologics.wordpress.com/2015/04/02/about-page-visibility-api-hidden-visibilitychange-visibilitystate/
> Reset pressing code on window.blur

- namui-cli/Cargo.lock
- namui-cli/Cargo.toml
- namui-cli/src/services/wasm_bundle_web_server.rs
I found that namui-cli bundle server couldn't read url if it use non-ascii url like korean. I decoded url before read file. 
Tested getting image with bundle after this fix.
> Decode encoded bundle url

- namui/src/namui/common/mod.rs
- namui/src/namui/draw/text.rs
- namui/src/namui/event/mod.rs
- namui/src/namui/render/text.rs
- namui/src/namui/render/text_input/draw_caret.rs
- namui/src/namui/render/text_input/get_selection_on_mouse_down.rs
- namui/src/namui/skia/base/paint_builder.rs
- namui/src/namui/skia/types.rs
- namui/src/namui/skia/web/canvas.rs
- namui/src/namui/skia/web/font.rs
- namui/src/namui/skia/web/paint.rs
When I render so many text, it makes lags so I optimized rendering and drawing text with cache.
before
after
(I reduced event count so comparison is not accurate.)
> Cache font information for optimization

- namui/src/namui/manager/web/mouse_manager.rs
When the wheel button was pressed, get_pressing_buttons() acted as if the right button was pressed.
> Fix get_pressing_buttons to return right buttons

- namui/src/namui/mod.rs
- namui/src/namui/render/rendering_tree/mod.rs
- namui/src/namui/render/special/attach_event.rs
Like wheel event, I suggest providing namui context in mouse event to get position of parent's location.
example:
```rs
parent.with_id(self.id)
// ...
children.attach_event(|builder| {
builder.on_mouse_down_in(|event| {
let parent_global_xy = event.context.get_rendering_tree_xy_by_id(self.id).unwrap();
let my_global_xy = event.context.get_rendering_tree_xy(event.target).unwrap();
let local_xy = my_global_xy - parent_global_xy;
})
});
```
I would like to use this code in namui animation editor to get the mouse local xy position in specific window.
> Provide context in mouse event

- namui/src/namui/mod.rs
Related slack message : https://projectluda.slack.com/archives/C015ELKQE67/p1656074655253679
Pros
- You don't have to send empty event to play video or animation.
Cons
- Drawing to monitor could be delayed
- But I don't think so because our render function is very cheap and fast. we already handle over 600 events(=600 renders) per second.
- There could be meaningless render if there are no video or animation.
Other Idea (that can be another answer so you have to take a look)
- Provide `fn namui::every_frame(rendering_tree: RenderingTree) -> RenderingTree` which return special rendering node, then namui will check on AnimationFrame event whether that `namui_context.rendering_tree` has `SpecialRenderingNode::EveryFrame` or not. If it exists then it will render before draw.
> Render before draw

- image-cropper/src/app/cropper/canvas/canvas.rs
- namui/src/namui/common/mod.rs
- namui/src/namui/event/mod.rs
- namui/src/namui/manager/mock/keyboard_manager.rs
- namui/src/namui/manager/mock/wheel_manager.rs
- namui/src/namui/manager/web/keyboard_manager.rs
- namui/src/namui/manager/web/wheel_manager.rs
- namui/src/namui/mod.rs
- namui/src/namui/render/rendering_tree/mod.rs
- namui/src/namui/render/special/attach_event.rs
Yes, Keyboard down and up.
- It's not enough to get keyboard event with NamuiEvent in user side because they want to bring the information that only can be captured in render fn. It's impossible to get props in event handler if they use NamuiEvent::KeyDown because NamuiEvent only has the information about namui, not rendering state.
No, I don't want to keep `self.selected_point_ids` in Self because it's just the props!
in render
in update. Oh yes!
> Support keyboard event

- namui-cli/src/services/wasm_bundle_web_server.rs
After this changes, it always fail to get bundle when user run `namui start` during build. after build, it will reload and everything become happy.
No need to open dev tools or disable cache. happpy
> Disable cache for bundle

- .github/workflows/namui-test-host-linux.yml
Github only protect merging pull request per job, not action. So I add post-test to make sure every tests have been passed.
> Put post-test job for pull request status check

- namui/src/namui/render/special/attach_event.rs
https://github.com/NamseEnt/namseent/blob/feature/animation-preset/namui-animation-editor/src/dial_counter/mod.rs#L171
it's super useful if user want to run event handler if mouse is in rendering tree!
> Check mouse in on wheel event

- namui/src/namui/mod.rs
- namui/src/namui/render/rendering_tree/mod.rs
- namui/src/namui/render/rendering_tree/visit.rs
- namui/src/namui/render/special/attach_event.rs
- namui/src/namui/render/special/mod.rs
- namui/src/namui/render/special/on_top.rs
- namui/src/namui/render/special/react.rs
`on_top` ignores clipping and draw in last order of drawing stage to draw on most top of display.
Previous :
https://user-images.githubusercontent.com/3580430/179544928-b1bc756e-ef8f-44ca-b25e-a57e3d81fdb8.mp4
After:
https://user-images.githubusercontent.com/3580430/179563138-62c9dc77-67f6-404d-a2dc-d8b32ab33f87.mp4
What I did
- add `on_top`
- add `stop_propagation` on mouse event
> Draw on top

- namui-cli/src/procedures/linux/wasm_linux_electron/start.rs
- namui-cli/src/procedures/linux/wasm_unknown_web/start.rs
- namui-cli/src/procedures/linux/wasm_windows_electron/start.rs
- namui-cli/src/services/rust_build_service.rs
Previously namui-cli didn't stop building when wasm-pack failed.
So I made it stop and exit process when wasm-pack failed, not cuz of cargo build.
I tested 
1) wasm-pack only error
2) cargo check error(it doesn't exit process.)
3) well-working source code without error
> Exit build on wasm-pack error #289

- namui-cli/electron/forge.config.js
- namui-cli/electron/src/main.js
- namui-cli/electron/src/namuiApi/deepLink.js
- namui-cli/electron/src/namuiApi/index.js
- namui-cli/src/procedures/linux/wasm_linux_electron/build.rs
- namui-cli/src/procedures/linux/wasm_linux_electron/start.rs
- namui-cli/src/procedures/linux/wasm_windows_electron/build.rs
- namui-cli/src/procedures/linux/wasm_windows_electron/start.rs
- namui-cli/src/services/electron_dev_service.rs
- namui-cli/src/util/mod.rs
- namui-cli/src/util/namui_deep_link_manifest/mod.rs
- namui-cli/src/util/namui_deep_link_manifest/namui_deep_link_manifest.rs
- namui/src/namui/common/mod.rs
- namui/src/namui/event/mod.rs
- namui/src/namui/namui_context/main_loop/post_update_and_render.rs
- namui/src/namui/namui_context/main_loop/pre_update_and_render.rs
- namui/src/namui/system/deep_link.rs
- namui/src/namui/system/mod.rs
Create a `.namuideeplink` file in the project root. The project root is where `.namuibundle` is located.
- One scheme per line.
- You can write comments with #.
ex)
```
luda-editor
other-scheme
```
will receive `luda-editor://some.url` and `other-scheme://other.url`
> Support deep link

- namui-cli/electron/src/main.js
- namui-cli/electron/src/namuiApi/index.js
- namui-cli/electron/src/namuiApi/openExternal.js
- namui/src/namui/common/mod.rs
- namui/src/namui/common/open_external.rs
Same as `shell.openExternal(url)`.
In most cases, it opens with a default browser rather than an electron.
Same as ` web_sys::window().unwrap().open_with_url_and_target(url, "_blank");`
> Support open external feature

- namui-cli/electron/src/main.js
Sometimes we need to bypass the cors. This is the simplest of many ways.
If there is a problem, we will have to use another method.
> Disable web security on electron

- namui-cli/src/procedures/linux/wasm_linux_electron/start.rs
- namui-cli/src/procedures/linux/wasm_unknown_web/start.rs
- namui-cli/src/procedures/linux/wasm_windows_electron/start.rs
- namui-cli/src/services/wasm_watch_build_service.rs
Some code should be not run.
When I change the code and run `namui start`, it will run previously built code which may not be able to run.
So I changed namui-cli to run browser or electron after first build.
> Start browser or electron after first build

- namui/src/namui/system/file/bundle/read_dir/load_bundle_metadata.rs
build failed in electron target but our ci didn't check in electron.
> Fix load_bundle_metadata for electron

- namui-cli/electron/src/main.js
This error occurs in Electron 20 and later versions.
It's related to [electron's update](https://www.electronjs.org/docs/latest/breaking-changes#default-changed-renderers-without-nodeintegration-true-are-sandboxed-by-default)
> Disable electron sandbox

- namui/src/namui/system/keyboard.rs
Related PR: #206 
Related Zulip: https://namseent.zulipchat.com/#narrow/stream/332914-.EA.B8.B0.EC.88.A0.EC.97.B0.EA.B5.AC.EC.86.8C/topic/Fix.20text-input.20space
I found that key-down's preventing default block input space and arrow keys. I fixed it.
Check list
- It still block alt+arrow key
- It doesn't block space and arrow key in text input
> Only prevent default on alt key

- namui/src/namui/namui_context/main_loop/post_update_and_render.rs
- namui/src/namui/skia/web/canvas.rs
- namui/src/namui/skia/web/canvas_kit/canvas.rs
I drew full page and I routed to other page, it didn't clear page. the previous page shows up.
Because all of our project draw in full scale. We always draw something using full screen. So I found this fault when I tried to draw empty after something.
No issue. If user want to stop clear canvas for best performance, I may make option about it. But it's fast sufficiently.
> Clear canvas before draw

- namui/src/namui/common/types/time.rs
I copied moment.js's method in https://momentjs.com/docs/#/displaying/fromnow/. Not very same, I removed months and years expression.
> Format relative time

- namui/src/namui/skia/web/image.rs
I found that `Image::new` was exposed in public even though nobody outside of crate cannot make canvaskit image.
> Change Image::new visibility only for inside of namui crate

- namui-cli/src/services/wasm_watch_build_service.rs
I found that `build` doesn't make runtime project
> Generate runtime project in build

- namui/Cargo.toml
- namui/sample/multiline-text/src/lib.rs
- namui/sample/text-input/src/lib.rs
- namui/src/namui/common/types/int_px.rs
- namui/src/namui/common/types/macros.rs
- namui/src/namui/draw/text.rs
- namui/src/namui/render/text.rs
- namui/src/namui/render/text_input/draw_caret.rs
- namui/src/namui/render/text_input/draw_texts_divided_by_selection.rs
- namui/src/namui/render/text_input/get_selection_on_mouse_down.rs
- namui/src/namui/skia/types.rs
- namui/src/namui/skia/web/font.rs
- namui/src/namui/system/font/mod.rs
- namui/src/namui/system/text_input.rs
https://user-images.githubusercontent.com/3580430/188393965-af8bade7-54d4-46c8-b47b-3af22a715b3a.mp4
Support multiple line text input
- In align right, it needs to put space(` `) width margin.
- Will fix if we need right-align text input later.
- Caret position is not exactly same between align.
- I think we don't have to fix it right now. it's very little pixel bug.
- Baseline won't work for multiline text input
- Will fix if we need not-top baseline text input later.
- TextInput system's variable name is still `inputElement` even I changed it to `HTML textAreaElement`
- I think we don't have to fix it because it's very similar both.
- overflow line break doesn't work
- Will be next pr.
> Support multinline text input

- namui/src/namui/system/file/mod.rs
- namui/src/namui/system/file/picker/mod.rs
The name `File dialog` is very ambiguous so I renamed it to `file picker`
> Rename file dialog to file picker

- namui/src/namui/namui_context/main_loop/post_update_and_render.rs
- namui/src/namui/render/text_input/mod.rs
- namui/src/namui/system/text_input/find.rs
- namui/src/namui/system/text_input/mouse_event.rs
- `on_top`'s mouse event filtering doesn't worked with text_input
- Because `on_top` mouse filtering was on [`call_mouse_event`](https://github.com/NamseEnt/namseent/blob/master/namui/src/namui/render/rendering_tree/mod.rs#L214), which called after [`text_input`'s `on_mouse_down_in`](https://github.com/NamseEnt/namseent/blob/03997970ec349e6babb1e44d02ca9d176e63805f/namui/src/namui/namui_context/main_loop/post_update_and_render.rs#L27).
- So I opened modal and clicked it, the text input behind the modal was clicked even I stop propagation.
- Called `text_input`'s mouse down event handler with `text_input` rendering tree's `attach_event`. So it finally works with `RenderingTree`'s `call_mouse_event` logic.
Tested in visual novel editor and namui text_input sample
> Apply on_top filter to text_input

- luda-editor/client/src/pages/sequence_edit_page/loaded/update/mod.rs
- luda-editor/client/src/pages/sequence_list_page/rename_modal.rs
- namui/sample/text-input/src/lib.rs
- namui/src/namui/render/text_input/mod.rs
- namui/src/namui/system/text_input/key_down.rs
- namui/src/namui/system/text_input/mod.rs
- namui/src/namui/system/text_input/mouse_event.rs
- Support keydown event like react
- Usage Example) you can stop input when `Enter` key down.
- Focus text input by api
- Usage Example) You can focus text input when you open modal.
- Current known issue: focus function may keep wrong selection.
- `enum Event` become nested.
> Support Keydown, Focus for text_input

- namui-prebuilt/src/scroll_view.rs
I found that previous code assumed bounding box has x:0, y:0 but sometime it isn't. So I fixed it.
> Fix wrong inner clip for scroll_view

- namui/src/namui/skia/web/canvas_kit/mod.rs
We had a error on github action, deploying luda editor to aws.
It wasn't reproduced in my local computer, so I couldn't figured out it.
I put allow for dead_code in canvas_kit module, it's ok to put that. at that module I only put canvas_kit external library things.
Deployment has been successful after allow dead_code.
> Allow dead_code for canvas_kit

- namui/src/namui/render/mod.rs
- namui/src/namui/render/padding.rs
- namui/src/namui/render/special/attach_event.rs
Support padding for rendering tree easily
Usage
```rust
typography::title::left_top("Image", Color::WHITE); // [Image]
typography::title::left_top("Image", Color::WHITE).padding(12.px()); // [  Image  ]
```
> Padding rendering tree

- namui/src/namui/common/text/line_texts.rs
- namui/src/namui/system/text_input/mouse_event.rs
https://user-images.githubusercontent.com/3580430/193572196-4710a63a-d0ec-4210-adad-f97b925ca40e.mp4
Previously we didn't calculated about baseline and y axis because I didn't use middle or bottom baseline text-input.
But for now, I use middle baseline text-input so I fixed it.
> Calculate text selection with y, baseline too

- image-cropper/src/app/cropper/render_app_bar.rs
- image-cropper/src/app/file_selector/file_selector.rs
- luda-editor/client/src/components/context_menu.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/render/filtered_image_list.rs
- namui-animation-editor/src/time_point_editor/wysiwyg_window/update/dragging/resize.rs
- namui-animation-editor/src/time_ruler/gradations.rs
- namui-prebuilt/src/button.rs
- namui-prebuilt/src/list_view.rs
- namui/src/namui/animation/image_keyframe_graph.rs
- namui/src/namui/common/types/angle.rs
- namui/src/namui/common/types/macros.rs
- namui/src/namui/common/types/mod.rs
- namui/src/namui/common/types/ratio.rs
- namui/src/namui/common/types/rect.rs
- namui/src/namui/draw/image.rs
- namui/src/namui/mod.rs
- namui/src/namui/render/matrix.rs
- namui/src/namui/render/rect.rs
When external crate tried to use `common_for_f32_type` macro of namui, there were error like below
```
error[E0119]: conflicting implementations of trait `std::ops::Mul<&f32>` for type `app::game::types::tile::Tile`
--> src/app/game/types/tile.rs:3:1
|
3 | namui::common_for_f32_type!(Tile, tile, TileExt);
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
| |
| first implementation here
| conflicting implementation for `app::game::types::tile::Tile`
|
= note: upstream crates may add a new impl of trait `namui::Ratio` for type `&f32` in future versions
= note: this error originates in the macro `$crate::_impl_binary_op_owned_borrowed` which comes from the expansion of the macro `namui::common_for_f32_type` (in Nightly builds, run with -Z macro-backtrace for more info)
```
The error point …
> Expose common_for_f32_type macro

- docker-images/namui-test-host/linux.Dockerfile
- namui-cli/src/procedures/linux/wasm_unknown_web/test.rs
I had a problem that `namui test` docker uses rust version 1.58.
let's fix the rust version of docker.
> Fix rust version 1.64

- .github/actions/init-test-job/action.yml
- .github/workflows/deploy-luda-editor.yml
I got a meessage from github action
and they said it's deprecated.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Fix deprecating set-output command

- luda-editor/client/src/pages/sequence_edit_page/loaded/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/render/top_bar.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/update/mod.rs
- namui/Cargo.toml
- namui/src/namui/system/file/download.rs
- namui/src/namui/system/file/mod.rs
- currently only string file download supported
- user can download luda-editor sequence in editor
local tested
> Support download file

- luda-editor/client/src/pages/sequence_edit_page/loaded/components/character_edit_modal/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/character_edit_modal/render/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/render/line_list/character_cell.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/update/mod.rs
Previously character edit modal opened in y:0, and I changed it to mouse's global_xy.
local tested.
> Open character edit modal on next to mouse cursor

- luda-editor/client/src/components/sequence_player.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/character_edit_modal/render/character.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_edit_modal/render/label_input.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/render/image_preview.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/render/label_list.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/render/line_list/mod.rs
- luda-editor/client/src/pages/sequence_list_page/rename_modal.rs
- namui/sample/multiline-text/src/lib.rs
- namui/src/namui/common/text/mod.rs
- namui/src/namui/draw/text.rs
- namui/src/namui/render/text.rs
- namui/src/namui/render/text_input/draw_caret.rs
- namui/src/namui/render/text_input/draw_texts_divided_by_selection.rs
- namui/src/namui/render/text_input/mod.rs
- namui/src/namui/system/text_input/mouse_event.rs
- Support line_height_percent for namui::text() and namui::text_input.
- put 150.percent line height for luda-editor's text boxes
Before
After
> Support line_height_percent for text parameter

- luda-editor/client/src/pages/sequence_edit_page/loaded/components/character_edit_modal/render/character.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_edit_modal/render/label_input.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/render/line_list/mod.rs
- luda-editor/client/src/pages/sequence_list_page/rename_modal.rs
- namui/sample/text-input/src/lib.rs
- namui/src/namui/render/text_input/draw_caret.rs
- namui/src/namui/render/text_input/mod.rs
- namui/src/namui/system/text_input/key_down.rs
- namui/src/namui/system/text_input/mouse_event.rs
Add padding for text_input
Tested in local with sample
https://user-images.githubusercontent.com/3580430/199461841-68d15482-4478-4dd0-b247-6883c7e34bfa.mp4
(padding was 10.px() in this test. now it become 4.px() as default)
> Add text_input padding

- luda-editor/client/src/pages/sequence_edit_page/loaded/render/mod.rs
I think we need the method to use responsive design in namui_prebuit::table.
> Put left-right margin for sequence edit

- namui/src/namui/render/text_input/mod.rs
- namui/src/namui/system/text_input/mod.rs
- namui/src/namui/system/text_input/mouse_event.rs
- namui/src/namui/system/text_input/post_render.rs
I think text_input is very unstable so I will make updates with PRs more.
- Support pub fn `focused_text_input_id(id)` and `last_focus_requested_text_input_id()`
- Remove `selection` from `Focus` event
- Call `Blur` and `Focus` on focus changed by Api
> Advance text input

- luda-adventure/src/app/game/render/translate_to_camera_screen.rs
- luda-adventure/src/app/game/types/game_object/player_character/player_character.rs
- luda-adventure/src/app/game/types/game_object/types/positioner.rs
- namui/src/namui/common/types/macros.rs
After
https://user-images.githubusercontent.com/3580430/198870476-258aa8d4-4a5f-4b3c-8bd6-146693967deb.mp4
The reason why the character is shaking is not about floor. I think it's about the problem of interpolation with skipping ticks.
Before this commit, look at the wall, it already has been shaked.
> Floor position to prevent flickering

- luda-editor/client/Cargo.lock
- luda-editor/client/Cargo.toml
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_edit_modal/update.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/render/label_list.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/render/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/update/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/update/upload_images.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_upload/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/update/mod.rs
-  User can upload multiple images at once using "Upload Bulk Images" button.
- To upload images using that button, user should rename image file with pattern `{label_key}={label_value}-{label_key}={label_value}.{extension}`. For example, `캐릭터=오하연-의상=평상복.png`
> Upload images at once

- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/update/upload_images.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_upload/mod.rs
- luda-editor/server/src/handle/mod.rs
- Failed to upload multiple images at once because of lambda throttle
- Fail to send some request in local even I disabled cache. It worked to send same api using curl in my git bash.
- Throttle and retry upload image request
- Add cache disable header (wink wink, small changes but I put in this PR.)
Tested in local and test server
> Throttle and retry upload image request

- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/render/image_preview.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/render/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/render/mod.rs
- namui-prebuilt/src/table/mod.rs
- namui-prebuilt/src/typography/mod.rs
Changes
1. Put text of cut in image editor
2. Bigger preview
3. Full-width image editor
> Improve image editor UI

- luda-editor/client/src/pages/sequence_edit_page/loaded/update/mod.rs
I wrote wrong code that, before getting `previous_image_ids`, I updated images so there were no `previous_image_ids`. It affected to Recent Images system so no recent images were showed on.
> Fix recent images

- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_manager_modal/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_manager_modal/render/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_manager_modal/update/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_table/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_table/render/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_table/render/row.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_table/update/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/render/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/render/top_bar.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/update/mod.rs
This Pr makes image manager for luda editor.
Image manager modal has big table or spreadsheet.
1. User can sort images using label key
2. User can update image's label value
I will put more functions, like (1) upload image, (2) delete image, (3) add new label key, (4) horizontal scroll, etc.
Demo
https://user-images.githubusercontent.com/3580430/202181629-4a56421b-f811-44fb-b386-c5110a4ea028.mp4
> Image manager

- luda-editor/rpc/src/define_rpc.rs
- luda-editor/rpc/src/lib.rs
We uses `spawn_local` to call async function like rpc so many times, but I think it's not necessary. I thought it can be done with callback. the good point of callback is we don't have to clone parameter of self from outside.
Before
After
> Support callback version for rpc

- luda-editor/client/src/components/context_menu.rs
Before
After
I think I should make a Color Palette for luda editor in separated file.
> Recolor context menu

- luda-editor/client/src/pages/sequence_edit_page/loaded/components/image_select_modal/render/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/components/screen_image_list/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/render/line_list/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/update/mod.rs
Previously, when I click right-side image list, it just open the image select modal. I wanted open context menu to copy-paste images.
I changed it to open context menu on right click the image list.
> Open context menu on mouse right down

- namui/src/namui/skia/web/canvas_kit/canvas_kit.rs
- namui/src/namui/skia/web/canvas_kit/surface.rs
- namui/src/namui/skia/web/surface.rs
- namui/src/namui/system/image.rs
When namui detect screen resize, it re-create canvaskit surface again, I followed [this](https://groups.google.com/g/skia-discuss/c/3c10MvyaSug).
We used `surface.makeImageFromTextureSource`, it makes the image that only can be used in that surface, so when we re-create surface by resize, all image created before doesn't work.
I changed the image creation logic to `canvaskit.MakeLazyImageFromTextureSource` which support reuse image for multiple surfaces.
Local resize tested
> Make canvaskit image reusable for multiple surfaces

- luda-editor/client/src/components/context_menu.rs
Previously on #445, I set context_menu item's background as RenderingTree::Empty when mouse isn't over that cell.
But that background used to be event handler also.
https://github.com/NamseEnt/namseent/blob/51bfa436822738e078c4603360409a79b1857760/luda-editor/client/src/components/context_menu.rs#L81-L83
I recovered it with this PR.
> Keep handle mouse over for context_menu

- namui/src/namui/render/text_input/mod.rs
- namui/src/namui/system/text_input/mod.rs
`text_input::EventHandler` from now on supports `on_text_updated`.
I will use this for sheet(#456) with below code,
https://github.com/NamseEnt/namseent/blob/58a6fc65f1fef0efecc262f7b5cfb80c96bca3f9/namui-prebuilt/src/sheet/cell/text_cell.rs#L76-L80
> Support on_text_updated for text_input event handler

- .github/workflows/namui-test-host-linux.yml
post-test never worked since it merged...!!!!!!!!!!!!!!!!!!!!
it's my fault, I didn't test it...
What was the problem
1. bash's `VARIABLE=VALUE` doesn't share that variable between other steps.
2. I didn't check true/false check
success case
failure case
Anycase, post-test runs. it should be failed on failure case.
How did I fix it
1. [Used github action environment](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable)
2. Test true/false cases
success case
failure case
Ok, it finally fails.
> Fix post-test works

- luda-editor/client/src/pages/sequence_edit_page/loaded/update/mod.rs
I forgot reset `text_input_selected_cut_id` on ESC key down at #403.
It's very necessary blurring text_input using esc to run undo.
> Blur list_list text_input after esc

- image-cropper/Cargo.lock
- luda-adventure/Cargo.lock
- luda-adventure/src/app/game/map/try_create_new_polygon.rs
- luda-adventure/src/component/collider/rigid_body/circle.rs
- luda-adventure/src/component/collider/rigid_body/collide_circle_to_polygon.rs
- luda-editor/client/Cargo.lock
- luda-editor/lambda-web/Cargo.lock
- luda-editor/server/Cargo.lock
- namui-cli/Cargo.lock
There was a compatibility issue while making luda-adventure. So I updated dependencies.
The update was excuted through injecting following code to `cargo-clean-check-fmt-all.py`
```python
print(f"cd {dir_path} && cargo update")
exit = os.system(
f"cd {dir_path} && cargo update")
if exit != 0:
print(f"\n\n-- fail cargo update on {dir_path}\n\n")
return
```
> Update cargo dependencies

- luda-editor/client/src/components/context_menu.rs
Previously, context menus were created through outside of screen and could not be clicked with the mouse. Modified to put the context menu always on the screen like other common applications.
https://user-images.githubusercontent.com/3580430/205364206-e0bbf5b8-5c7f-4022-be4b-d072021a4fe4.mp4
> Keep context menu within screen

- namui/sample/text-input/src/lib.rs
- namui/src/namui/common/text/glyph_group.rs
- namui/src/namui/common/text/line_texts.rs
- namui/src/namui/common/text/measure_glyphs.rs
- namui/src/namui/common/text/mod.rs
- namui/src/namui/common/text/multiline_caret.rs
- namui/src/namui/common/text/text_width.rs
- namui/src/namui/draw/text.rs
- namui/src/namui/render/text.rs
- namui/src/namui/render/text_input/draw_caret.rs
- namui/src/namui/render/text_input/draw_texts_divided_by_selection.rs
- namui/src/namui/render/text_input/mod.rs
- namui/src/namui/skia/base/paint_builder.rs
- namui/src/namui/skia/web/font.rs
- namui/src/namui/skia/web/paint.rs
- namui/src/namui/system/font/mod.rs
- namui/src/namui/system/text_input/key_down.rs
- namui/src/namui/system/text_input/mod.rs
- namui/src/namui/system/text_input/mouse_event.rs
- namui/src/namui/system/text_input/selection.rs
Closes #474 
I found that,
1. js's String.length is not the same with utf8 character length. they counted utf16 code units. I changed our logic only uses with the length of utf-8 chars
2. There were some logics which missed font fallbacks. I filled that.
> Handle utf16 multiple length selection problem with font fallback

- namui/src/namui/system/font/mod.rs
- namui/src/namui/system/typeface/load_sans_typeface_of_all_languages.rs
- namui/src/namui/system/typeface/mod.rs
Loads default font of FontFace during init.
*default font is a 12px font.
**12px is namui_prebuilt::typography's body font size.
Freezing occurs when text is first drawn in an adventure. 
This occurs first once per FontFace, regardless of font size.
So preload default font on init time.
> Load default font of typeface on init

- luda-editor/server/Cargo.lock
- luda-editor/server/Cargo.toml
- luda-editor/server/src/services/auth/documents/mod.rs
- luda-editor/server/src/services/auth/documents/user/mod.rs
- luda-editor/server/src/services/auth/documents/user/previous/mod.rs
- luda-editor/server/src/services/auth/documents/user/previous/v0.rs
- luda-editor/server/src/services/auth/documents/user/v1.rs
- luda-editor/server/src/services/auth/get_or_create_user.rs
- luda-editor/server/src/services/auth/impls.rs
- luda-editor/server/src/services/auth/mod.rs
- luda-editor/server/src/services/auth/user_identity.rs
Previously, `UserDocument` didn't have username. I added it with `migration` crate which support struct version migration.
Local tested.
> Add username for luda-editor user

- luda-adventure/src/app/game/game.rs
- luda-adventure/src/app/game/image_loader.rs
- luda-adventure/src/app/game/mod.rs
Load all images on start.
No waiting for loading now. If It takes too long because of more images in the future, we will need a loading splash.
> Load all images on start

- namui-type/src/types/vector_types/wh.rs
I call too much of `Rect::from_xy(Xy::zero(), wh)`, it's too long to type. I HATE IT AND I WANT TO STOP IT!!
> Wh.to_rect()

- namui/src/namui/common/text/glyph_group.rs
- namui/src/namui/common/text/line_texts.rs
- namui/src/namui/common/text/measure_glyphs.rs
- namui/src/namui/common/text/mod.rs
- namui/src/namui/common/text/multiline_caret.rs
- namui/src/namui/common/text/text_width.rs
- namui/src/namui/draw/text.rs
- namui/src/namui/render/text.rs
- namui/src/namui/render/text_input/draw_caret.rs
- namui/src/namui/render/text_input/draw_texts_divided_by_selection.rs
- namui/src/namui/render/text_input/mod.rs
- namui/src/namui/skia/base/paint_builder.rs
- namui/src/namui/skia/web/font.rs
- namui/src/namui/skia/web/paint.rs
- namui/src/namui/system/text_input/key_down.rs
- namui/src/namui/system/text_input/mouse_event.rs
Removed too much of referencing of Paint, and just keep using Arc<Paint> as possible.
> Keep use Arc<Paint> as possible

- luda-editor/client/Cargo.lock
- luda-editor/client/Cargo.toml
- luda-editor/client/src/app/mod.rs
- luda-editor/client/src/pages/project_list_page/mod.rs
- luda-editor/client/src/pages/router.rs
- luda-editor/client/src/pages/sequence_edit_page/loaded/render/top_bar.rs
- luda-editor/client/src/pages/sequence_list_page/mod.rs
I added `wasm-bindgen` to luda-editor for subscribing `hashchange` event.
`hashchange` event will also be fired on forward/backward button of browser clicked.
so we can move between pages using forward/backward button.
If we don't need this feature, we can remove `wasm-bindgen`.
> Route with hash

- namui/src/namui/system/keyboard.rs
- namui/src/namui/system/text_input/mod.rs
- on keyboard Enter, I focused text_input
- What I expected
- Just focus text_input without text changes
- What happened
- text_input focused but also changed text (\n)
To prevent this problem, I trap the keydown event in text_input. This solve the problem.
Also removed alt_key checking on document.on_key_down because that was only for text_input. From now on, we don't need it.
> Trap keydown event in text_input

- namui-cli/src/procedures/linux/wasm_unknown_web/test.rs
Purpose: to run test in local even though there is unpolished codes
tested 1. run with empty flags
tested 2. run with env flags
> Pass rustflags to test, not default setting

- namui/src/namui/system/keyboard.rs
There are many code which want to know whether shift key is pressed or not, but the problem is there are left and right shift key, so the code become longer than expect.
I put simple way to check shift, ctrl, alt key pressed.
> Easy way to call [shift, ctrl, alt]_press()

- namui/src/namui/render/rendering_tree/mod.rs
Previously on_mouse wasn't called when in/out func is none. Changes to invoke on_mouse.
> Invoke on_mouse even in/out func is none

- .github/workflows/deploy-luda-editor.yml
- .github/workflows/destory-luda-editor.yml
`GITHUB_REF` will be `master` on delete branch event, even when the deleted branch is not `master`, but `delete event` uses the github action file of master branch.
> Get branch name from event.ref

- namui/src/namui/system/keyboard.rs
This PR does 2 things
1. Allow `jump to tab` (ctrl + 0 ~ 9)
2. Use keyboard event's ctrl, alt, shift state for right pressing status.
a. Without this change, user cannot jump out and in again because namui reset pressing keys on blur of window. try ctrl+1, ctrl+2, ctrl+1, ctrl+2.
I want to use second implementation for general cases with pressing_keys, but it's not possible for now. Browser doesn't give use enough information which key was pressed just before we jump to namui's tab. I hope browser supports that features later.
> Allow jump to tab with keyboard, fixing reset problem

- cargo-clean-all.py
This is useful when you have a problem with big target directories.
> Add cargo-clean-all.py

- .github/actions/init-test-job/action.yml
I read some comment that `**/cargo.lock` doesn't work for cache path, but relative path would work(`./**/cargo.lock`), so I tested and it works!
> Fix wrong cache path

- namui/src/namui/render/rendering_tree/bounding_box.rs
I tried to use table in scroll_view. But it was shown as follows.
*Red rect is bounding box
After this pr. It will be shown as follows.
> Clip bounding box with transformed

- luda-editor/server/server-core/src/lib.rs
There is infinite pending problem on chrome.
This seems to be more relevant to port forwarding of vscode or ssh tunneling than keepalive.
So enable keepalive for now.
> Enable keepalive in luda editor server

- luda-editor/client/src/pages/sequence_edit_page/loaded/components/character_editor/render/part_picker.rs
> Hide always-on cg parts on cg picker

- namui/src/namui/skia/web/canvas_kit/runtime_effect.rs
- namui/src/namui/skia/web/runtime_effect.rs
`@param isOpaque` seems to be deprecated.
> Update makeShaderWithChildren function of canvaskit

- .github/workflows/publish-extension.yml
Github actions doesn't call another github actions in single github-token so this fucking workflows never invoke push:tag. si bal
> Release and publish in single workflow

- cargo-check-and-fmt-all.py
- cargo-clean-all.py
- cargo-clean-check-fmt-all.py
- cargo-fix-fmt-all.py
- cargo-metadata-all.py
- cargo-update-all.py
There was trailing `\n` in ignored_project paths.
This pr strips '\n'.
> Strip whitespace of ignored project paths

- namui-cli/src/main.rs
- namui-cli/src/procedures/build/mod.rs
- namui-cli/src/procedures/linux/wasm_linux_electron/build.rs
- namui-cli/src/procedures/linux/wasm_unknown_web/build.rs
- namui-cli/src/procedures/linux/wasm_windows_electron/build.rs
- namui-cli/src/services/electron_build_service.rs
- namui-cli/src/services/wasm_watch_build_service.rs
- namui-cli/src/services/wasm_web_runtime_watch_build_service.rs
Don't use futures block_on on tokio runtime
> Fix wrong block_on usage in namui-cli

- luda-editor/rpc/src/data/cut_update_action.rs
I used `swap_remove()` on `cut.screen_graphics` because I just heard It is faster than `remove()`.
But `swap_remove()` changes `cut.screen_graphics`'s order.
> Fix DeleteGraphic action to keep graphic order

- luda-editor/server/server-core/src/handle/mod.rs
- luda-editor/server/server-core/src/session/mod.rs
- luda-editor/server/server-core/src/storage/dynamo_db/singular.rs
- luda-editor/server/server-core/src/storage/dynamo_db/transact.rs
It's difficult to debug on cloud watch logs
> No linebreak for server logs

- namui-cli/webCode/src/worker.ts
- skia/canvas-kit-wasm-bindgen/src/canvas_kit.rs
- skia/skia/src/canvas_kit/surface.rs
Closes #630 
The key solution is resizing canvas on `requestAnimationFrame`.
Additional changes: Add option for `MakeWebGLCanvasSurface`. I thought it can help this issue but it wasn't. but anyway I changed that code so I put on this PR.
> Fix blinking during screen resize

- luda-editor/psd/src/sections/image_resources_section.rs
- luda-editor/psd/src/sections/mod.rs
We had psd parsing problem. https://namseent.zulipchat.com/#narrow/stream/332914-.EA.B8.B0.EC.88.A0.EC.97.B0.EA.B5.AC.EC.86.8C/topic/.E2.9C.94.20psd-parsing-problem
I made a mistake removing image resource name parsing at https://github.com/NamseEnt/namseent/commit/d353bf0517572fb3162f0707dac907d74d65f018#diff-0e209d1a09f8eee1ed5c699c1df7b0fd7546320b7a6ee41f852021045eb380b3L88 , in PR #609 
This PR Restore broken parsing part
> Restore image resource name parsing

- luda-editor/client/src/pages/sequence_edit_page/components/cut_list_view/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/components/graphic_list_view/mod.rs
- luda-editor/client/src/pages/sequence_edit_page/components/wysiwyg_editor/change_graphic_order.rs
- luda-editor/client/src/pages/sequence_edit_page/sequence/mod.rs
- luda-editor/rpc/src/data/cut_update_action.rs
- luda-editor/rpc/src/data/sequence_update_action.rs
- luda-editor/server/server-core/src/apis/sequence/update_sequence.rs
Order changing functions works like
1. Remove self
2. Insert self after `after_*`
If `after_*` is indicating self, Inserting after `after_*` is impossible because self is already removed.
So ignore order change request if `after_*` is indicating self.
> Prevent change order to after itself

- luda-editor/rpc/src/data/screen_graphic/v1.rs
It was for testing when I working on rotation feature, but it was not restored at that time.
> Fix new image to be created with zero rotation

- luda-editor/client/src/pages/mod.rs
- luda-editor/client/src/pages/project_acl_manage_page/mod.rs
- luda-editor/client/src/pages/project_acl_manage_page/top_bar.rs
- luda-editor/client/src/pages/project_list_page/mod.rs
- luda-editor/client/src/pages/router.rs
- luda-editor/client/src/pages/sequence_list_page/mod.rs
- luda-editor/rpc/src/lib.rs
- luda-editor/server/document-macro/src/lib.rs
- luda-editor/server/server-core/src/apis/mod.rs
- luda-editor/server/server-core/src/apis/project/edit_user_acl.rs
- luda-editor/server/server-core/src/apis/project/list_editable_projects.rs
- luda-editor/server/server-core/src/apis/project/list_user_acls.rs
- luda-editor/server/server-core/src/apis/project/mod.rs
- luda-editor/server/server-core/src/storage/dynamo_db/singular.rs
- luda-editor/server/server-core/src/storage/dynamo_db/transact.rs
We need better solution for adding user to project editor. #711
- Manage acl
- ![image](https://github.com/NamseEnt/namseent/assets/38313680/38876a5a-493d-4c48-aa53-e242c1e2e021)
- Copy user id
- ![image](https://github.com/NamseEnt/namseent/assets/38313680/3f7b0ffc-d472-4f22-a5e7-3fd43a0c3bf9)
- List editor granted project also
- Previously, only projects owned were listed
- `update or create` command in db.
Closes #407
> Add user acl management page

- namui/skia/skia/src/native/path.rs
`fill_path_with_paint` can return false but that's expected behavior.
That's commented on `fill_path_with_paint`.
/// Returns: `true` if the dst path was updated, `false` if it was not (e.g. if the path
///                  represents hairline and cannot be filled).
> Don't panic on fill_path_with_paint

- namui/namui-cli/src/services/resource_collect_service.rs
Without pdb file, backtrace shows `<unknown>` so I added it.
> Use pdb for backtrace

- namui/namui/src/namui/mod.rs
- namui/namui/src/namui/system/media/audio/audio_buffer.rs
- namui/namui/src/namui/system/media/audio/audio_context.rs
- namui/namui/src/namui/system/media/audio/audio_resampling.rs
- namui/namui/src/namui/system/media/audio/full_load_once_audio.rs
- namui/namui/src/namui/system/media/audio/mod.rs
- namui/namui/src/namui/system/media/core/media_core.rs
- namui/namui/src/namui/system/media/core/open_media.rs
- namui/namui/src/namui/system/media/media_context.rs
- namui/namui/src/namui/system/media/mod.rs
- namui/sample/media/src/lib.rs
FullLoadOnceAudio is the audio which load all at creation and support slice by duration.
I made it instead of media because media support video, and clipping video could be not that much accurate. To make it more accurate, I made audio-only simple version.
Check media sample to know how to use.
> Full-load-once audio with slice support

- namui/namui-cli/src/services/runtime_project/wasm.rs
- namui/namui-cli/src/services/runtime_project/x86_64_pc_windows_msvc.rs
- namui/namui-cli/src/services/rust_build_service.rs
- namui/namui-cli/src/util/mod.rs
- namui/namui-cli/src/util/recreate_dir_all.rs
Previously I turned on target feature in wrong way so it doesn't worked when we do wasm platform.
I turned on target features, which supported by 99% of steam users' cpu.
Only once tested.
tested code
```rust
fn consume(&mut self, output: &mut [f32]) {
self.buffer
.drain(..output.len())
.zip(output)
.for_each(|(src, dst)| {
*dst += src;
});
}
```
avg: 45.824µs
avg: 49.48µs // what!? but it's possible because I only tested once.
avg: 8.42µs
avg: 7.828µs
> Turn on target feature based on steam hw survey

- namui/namui/src/namui/system/media/audio/full_load_once_audio.rs
> Optimize full_load_once_audio consume using VecDeque

- namui/namui-type/src/types/data_structure/cheap_slice.rs
- namui/namui-type/src/types/data_structure/mod.rs
This is the generic version of bytes::Bytes(https://docs.rs/bytes/latest/bytes/struct.Bytes.html).
It support O(1) slice using Arc-ed source and offset-length management.
Very useful for audio system.
> Add cheap_slice

- luda-editor/server/server-core/src/storage/dynamo_db/singular.rs
I found that `update_or_create_item` didn't put prefix.
> Put prefix on update_or_create_item

- namui/namui/src/namui/system/media/audio/full_load_once_audio.rs
Below code doesn't work,
```rust
let audio_futures = ["no_drums", "cymbals", "toms", "snare", "kick"].map(|file_name| {
FullLoadOnceAudio ::load(
&namui::system::file::bundle::to_real_path(format!(
"bundle:resources/{file_name}.opus"
))
.unwrap(),
Some(SAMPLE_RATE),
)
});
```
Because of lifetime.
No need for refernece. I removed it.
> Remove reference for path

- namui/namui-cli/src/services/runtime_project/x86_64_pc_windows_msvc.rs
1. LTO doesn't make our game faster than I expected. it really not works.
2. opt-2 for debug makes pretty good performance and re-build time is really good (5sec)
> Remove lto, but use opt for debug

- hololive-beat/hololive-beat/Cargo.lock
- hololive-beat/note-register/Cargo.lock
- namui/namui-drawer/sys/Cargo.lock
- namui/namui-prebuilt/Cargo.lock
- namui/namui-type/Cargo.lock
- namui/namui-type/Cargo.toml
- namui/namui-type/src/types/units/matrix.rs
- namui/namui/Cargo.lock
- namui/namui/src/namui/bounding_box/rendering_tree/visit.rs
- namui/skia/skia/Cargo.lock
- namui/skia/skia/src/native/canvas.rs
Reason: it's slower than simple [[f32; 3;] 3;] for multiplication.
before: 6us
after: 200ns
(debug mode)
> Remove nalgebra for performance reason

- namui/namui/src/namui/hooks/image.rs
With previous code, it infinitely called effect because it ran set_load, so load's sig updated.
I unwrap it from sig to just bool.
> Prevent running effect by load update

- namui/namui-hooks/src/set_state.rs
- namui/namui-hooks/src/world/mod.rs
State don't have to be `Sync` because it's only accessed by one thread.
> Remove unnecessary `Sync` trait of state

- namui/namui-hooks/src/atom.rs
I believe it's ok to expose that.
I'm using server connection as atom, so I need to check whether atom(connection) is initialized or not, to try connect to server.
> Expose `Atom::is_initialized`

- namui/namui-cli/src/services/wasi_cargo_envs.rs
latest cc crate need that environment variable for wasi target.
https://github.com/rust-lang/cc-rs/blob/bffb5c009699bdf85c27bfedf60ed631fb679efd/src/lib.rs#L3932-L3941
https://github.com/rust-lang/cc-rs/issues/1109
> Add WASI_SYSROOT for wasi env

- namui/namui-hooks/Cargo.toml
- namui/namui-hooks/src/component/ctx/public_crate.rs
- namui/namui-hooks/src/component/instance.rs
- namui/namui-hooks/src/render_ctx/mod.rs
- namui/namui-hooks/src/test/mod.rs
1. Add `ctx.spawn` which automatically abort future on component unmount.
2. I forgot implement effect clean up call. Add that feature.
> ctx.spawn(future) and Clean up

- namui/namui-prebuilt/src/dropdown/mod.rs
- namui/namui-prebuilt/src/list_view.rs
This can reduce the memory usage because it doesn't use Vec.
I'm not sure actually 'into_iter' or 'iter' allocate memory on heap. ahaha
> Use Iterator for list_view

- namui/namui-hooks/src/component/ctx/public_crate.rs
- namui/namui-hooks/src/component/instance.rs
- namui/namui-hooks/src/ids.rs
- namui/namui-hooks/src/set_state.rs
- namui/namui-hooks/src/test/mod.rs
- namui/namui-hooks/src/world/mod.rs
- namui/namui-hooks/src/world/public.rs
Changes
1. Size of `SetStateItem` become 56 bytes to support multiple sig ids, but I think it's ok.
2. Multi-mutate only works with state for now. No support for atom yet.
3. unsafe code added for short and low overhead code. it's on getting multiple states' reference.
Usage
```rust
(set_state1, set_state2).mutate(|(state1, state2) { ... });
```
> Support 2,3,4 tuple set_state mutate

- namui/namui-cli/build.rs
Wasi sdk download url changed in version 23 and above.
https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-23
> Update wasi sdk url for version 23 and above

- luda-editor/psd-sprite-render/src/render_psd_sprite.rs
The image filter does not seem to be affected by the path. So I did scale and translate manually.
> Fix sprite size to be affected by wh

- luda-editor/nimg/Cargo.lock
- luda-editor/nimg/Cargo.toml
- luda-editor/nimg/src/lib.rs
- luda-editor/psd-sprite-render/Cargo.lock
- luda-editor/psd-sprite-render/Cargo.toml
- luda-editor/psd-sprite-render/src/render_psd_sprite.rs
- luda-editor/psd-sprite-render/src/sprite_image_ext.rs
- luda-editor/psd-sprite/src/encode.rs
- luda-editor/psd-sprite/src/psd_sprite.rs
```
PsdSprite::from_psd_bytes: 527.779713ms
psd_sprite.image_encoded_byte_size: 1,176,055
before zstd: 1,176,055
full_encoded.len(): 1,027,876
zstd::decode_all: 405.731µs
create_image_filter: 31.124447ms
```
fast enough. I'm gonna do about streaming decoding next.
> nimg: Jpg and Zstd as main codec

- namui/namui-cli/webCode/src/RingBufferWriter.ts
- namui/namui-cli/webCode/src/bufferPool.ts
- namui/namui-cli/webCode/src/httpFetch/httpFetch.ts
- namui/namui-cli/webCode/src/httpFetch/noStream.ts
- namui/namui-cli/webCode/src/httpFetch/yesStream.ts
- namui/namui-cli/webCode/src/imports/importObject.ts
- namui/namui-cli/webCode/src/insertJs.ts
- namui/namui-cli/webCode/src/interWorkerProtocol.ts
- namui/namui-cli/webCode/src/main.ts
- namui/namui-cli/webCode/src/newEventSystem.ts
- namui/namui-cli/webCode/src/webSocket.ts
- namui/namui-cli/webCode/tsconfig.json
- namui/namui/Cargo.lock
- namui/namui/Cargo.toml
- namui/namui/src/lib.rs
- namui/namui/src/system/mod.rs
- namui/namui/src/system/network/http/mod.rs
- namui/namui/src/system/network/http/non_wasi.rs
- namui/namui/src/system/network/http/wasi.rs
- namui/namui/src/system/skia/mod.rs
- namui/namui/src/system/wasi/buffer_pool.rs
- namui/namui/src/system/wasi/insert_js.rs
- namui/namui/src/system/wasi/mod.rs
- namui/namui/src/system/wasi/new_event_system/event.rs
- namui/namui/src/system/wasi/new_event_system/mod.rs
- namui/sample/http/.gitignore
- namui/sample/http/Cargo.lock
- namui/sample/http/Cargo.toml
- namui/sample/http/src/lib.rs
- namui/sample/media/Cargo.lock
This PR exposes [http](https://docs.rs/http/latest/http/) crate as interface for http request and response.
I put some Extension traits of http::Request and http::Response, so user can send and receive using that trait.
Windows: need tokio update (https://github.com/tokio-rs/tokio/pull/6822), because hyper-util's dns system use original tokio.
Wasi: Works well.
google's fail is natural because google server blocks our request by cors policy.
1. `new-event-system` added. I will put every js-rs event things in here, including pre-made other event systems, like websocket, screen, etc.
> Namui New http wrapping

- namui/namui-cli/webCode/src/httpFetch/yesStream.ts
`buffer.buffer.byteLength` returns full length of memory, not the view's length.
> Fix wrong length setting for http stream buffer

- namui/namui-cli/webCode/src/httpFetch/yesStream.ts
Previously, the duplex mode setting was not applied, resulting in the following error:
```text
[WASI stderr(tid: 2)] http_fetch_on_error: TypeError: Failed to execute 'fetch' on 'Window': The `duplex` member must be specified for a request with a streaming body
```
> Set duplex on fetch start

- namui/namui-hooks/src/render_ctx/dependencies.rs
Previously it couldn't check the first time calling.
> Track eq for () too

- namui/namui-cli/webCode/src/insertJs.ts
Without this PR, inserting multiple js makes error because `const namui_sendData` is on the same top scope.
> Put namui_sendData in block scope

- luda-editor/new-client/src/episode_editor/scene_preview.rs
- luda-editor/new-client/src/episode_editor/scene_sprite_editor/mod.rs
- luda-editor/new-client/src/episode_editor/scene_sprite_editor/size_tool.rs
> Optimize size tool

- luda-editor/new-client/src/episode_editor/mod.rs
- luda-editor/new-client/src/episode_editor/text_editor.rs
- 1sec delayed update
- no new line allowed
> Add text editor for character line

- luda-editor/new-client/src/audio_util/audio_storage.rs
- luda-editor/new-client/src/audio_util/mod.rs
- luda-editor/new-client/src/episode_editor/mod.rs
- luda-editor/new-client/src/episode_editor/properties_panel.rs
- luda-editor/new-client/src/episode_editor/scene_audio_editor/audio_select_tool.rs
- luda-editor/new-client/src/episode_editor/scene_audio_editor/mod.rs
- luda-editor/new-client/src/episode_editor/scene_audio_editor/volume_tool.rs
- luda-editor/new-client/src/lib.rs
- luda-editor/new-server/rpc/src/types/scene.rs
- list audio assets
- set bgm
- set volume
- preview on hovering
- 1~2 sec delayed
> Add scene audio editor

- namui/namui-cli/src/cli.rs
- namui/namui-cli/src/main.rs
- namui/namui-cli/src/procedures/linux/wasm32_wasi_web/build.rs
- namui/namui-cli/src/procedures/linux/wasm32_wasi_web/start.rs
- namui/namui-cli/src/procedures/linux/wasm32_wasi_web/vite_config.rs
- namui/namui-cli/src/procedures/linux/x86_64_pc_windows_msvc/build.rs
- namui/namui-cli/src/procedures/linux/x86_64_pc_windows_msvc/start.rs
- namui/namui-cli/src/procedures/start.rs
- namui/namui-cli/src/services/bundle/bundle_to_sqlite.rs
- namui/namui-cli/src/services/runtime_project/mod.rs
- namui/namui-cli/src/services/runtime_project/wasm.rs
- namui/namui-cli/webCode/expressPlugin.ts
- namui/namui-cli/webCode/package-lock.json
- namui/namui-cli/webCode/package.json
Sqlite Vacuum changes bundle.sqlite file binary value so ETag changed, browser couldn't load it from cache. So I keep calling vacuum only if something really changed.
Also Brotli compression added for vite server.
+ Add option to Strip debug info
> Compress payloads, Keep cache bundle, Strip debug info

- tower-defense/src/game_state/flow.rs
- tower-defense/src/game_state/mod.rs
- tower-defense/src/tower_selecting_hand/mod.rs
- tower-defense/src/tower_selecting_hand/tower_preview.rs
It was the best record, but the game crashed because of this
> Fix left reroll chance counting for prevent error from extra reroll

- namui/namui/src/lib.rs
I hope namui exposes crates that use by rust community generally, as de facto.
For example, rand is most used crate (I guess!?!?) for random generation.
> Expose rand

- namui/namui-hooks/benches/translate_benchmark.rs
- namui/namui-hooks/src/compose/ctx/mod.rs
- namui/namui-hooks/src/compose/ctx/public/event.rs
- namui/namui-hooks/src/compose/ctx/public/stack.rs
- namui/namui-hooks/src/render_ctx/dependencies.rs
- namui/namui-hooks/src/test/mod.rs
- namui/namui-hooks/src/test/mouse_event.rs
- namui/namui-hooks/src/test/pass_sig.rs
- namui/namui-hooks/src/world/mod.rs
- namui/namui-hooks/src/world/public.rs
- namui/namui-prebuilt/src/table/tests.rs
- namui/namui-type/src/types/units/rect.rs
- namui/namui/src/hooks/looper.rs
- namui/namui/src/system/skia/mod.rs
I found that mouse xy in test doesn't work well with ``ctx.translate`.
As quick fix, I removed converting mouse xy to local xy during bounding box check.
It mean, if we rotate Rect and test mouse in, it will return false answer on the left-top, right top, and bottoms also because it only handle with bounding box, not path itself.
I will change that later.
> Use global xy for mouse xy in test
